### ISSUE TITLE
 FYI: Piwik Tracking API now allows data up to 24 hours in the past  

### ISSUE THREAD

**Issue by mattab** [piwik/piwik-sdk-ios#100]
Dear SDK maintainer & SDK users, 

Here is a quick notice regarding an important Tracking API improvement in Piwik 3: it is now possible to store data in the past up to 24 hours in the past. In Piwik 2, only data up to 4 hours could be stored in the past. This would hopefully help build a useful offline tracking mechanism in the iOS SDK later. This core improvement was done in: https://github.com/piwik/piwik/issues/10968

As there is likely nothing to do feel free to close the issue.

If you have any question or suggestion  we're here to help :) 

Cheers!

**Comment by brototyp** [comment]
Thanks @mattab, we will consider this when queueing and transmitting events in the Swift rewrite.

**Comment by brototyp** [comment]
@mattab The Documentation should be refreshed. Here the old 4h rule is still stated: http://developer.piwik.org/api-reference/tracking-api#other-parameters-require-authentication-via-token_auth

**Comment by mattab** [comment]
Thanks for the note @brototyp - done!
