### ISSUE TITLE
Custom Dimension Tracking

### ISSUE THREAD

**Issue by brototyp** [piwik/piwik-sdk-ios#111]
- [x] ~Adding Custom Dimensions in the Visit Scope [Pull Request](https://github.com/piwik/piwik-sdk-ios/pull/132)~
- [x] Adding Custom Dimensions for the Action Scope

**Comment by jmoukel** [comment]
Just wondering. When are you guys planing to release this?

**Comment by brototyp** [comment]
Hi @jmoukel, thanks for asking. I just did the final touches on the Pull Request that adds the Custom Dimensions for the Visit Scope. For the 4.1 release only the #118 is left. I think it will be finished later this month. If you can't wait, just try the development branch.

**Comment by brototyp** [comment]
Also: Feedback on the Custom Dimensions implementation is welcome. I am currently not sure how important the Action Scope is.

**Comment by jmoukel** [comment]
Hi @brototyp ,

Sounds good, thanks. I'll wait until you finish it 💯 given it might be ready soon. Good job, btw.

I'm new with Piwik, but it seems the scope is very important for _Custom Dimensions_. I can see myself using the scope "**Action**" in my apps and I will definitely use the scope "**Visit**". I mean, I found very useful to report info both visit-wise (_e.g. app version being used_) and action-wise (_e.g. device volume when Play button was pressed_).

**Comment by jmoukel** [comment]
Hi @brototyp ,

I saw you added Visit scope Custom Dimensions to the main branch. Pretty cool indeed.

_Did you decide to also add Action scope custom dimensions?_ No rush or anything.

**Comment by jmoukel** [comment]
Hi @brototyp !
Just wondering, when are you guys planing to release the **Action Scope** Custom Dimensions?

Thanks :]

**Comment by brototyp** [comment]
Hi @jmoukel, thanks for nudging. Sometimes I need someone to remind me about a certain feature. I focussed on implementing #153 where I think we have a near to final pull request in #188.

Once this PR is through, I will focus on this one here.

**Comment by jmoukel** [comment]
Thank you :] @brototyp

**Comment by brototyp** [comment]
It just got merged and will be part of the next release

**Comment by brototyp** [comment]
Just released [version 4.4.0](https://github.com/piwik/piwik-sdk-ios/releases/tag/v4.4.0) containing this feature.
