### ISSUE TITLE
Getting Coredata error while using GMSMapView 

### ISSUE THREAD

**Issue by vinaykmr889** [piwik/piwik-sdk-ios#116]
i am getting coredata error when i am trying to use GMSMapView in my project. I am using coredata in my project. I just replaced apple map to google map and i started getting this problem.  **[error] error: The current thread is not the recognized owner of this NSManagedObjectContext(0x6000001d03b0).  Illegal access during objectRegisteredForID:
CoreData: error: The current thread is not the recognized owner of this NSManagedObjectContext(0x6000001d03b0).  Illegal access during objectRegisteredForID:**

**Comment by brototyp** [comment]
Hi @vinaykmr889, thanks for your report. Are you possibly tracking any Piwik events from a background thread? Can you give us a Stacktrace?

**Comment by brototyp** [comment]
Closing this for now. Feel free to reopen if you have more information on this topic.
