### ISSUE TITLE
about performance 

### ISSUE THREAD

**Issue by icoco** [piwik/piwik-sdk-ios#123]
I have install the server and run the demo ios code, that is great code I think.

just one question, I see the server part code 'piwik.php' which is the entry api of the mobile sdk, 
I think that seem the code do much jobs which probably effect the performance of the track action, as we know, app just post tracked data to server, server duty to store the data and Analytics later, 

maybe the entry api just need store the data somewhere immediately then return to client, another  job duty to re-post the data to 'piwik.php' as before then it will got more better performance for mobile app ... 

 is it correct  ?

**Comment by icoco** [comment]
looks  swoole can be used for this purpose

**Comment by brototyp** [comment]
Hi @icoco, thanks for your feedback and your suggestion. This repository is basically just for the iOS sdk. Do you mind copying your issue over to the repository for the piwik core repository? https://github.com/piwik/piwik
