### ISSUE TITLE
Rewrite Documentation to match new Swift-sdk-usage

### ISSUE THREAD

**Issue by brototyp** [piwik/piwik-sdk-ios#125]

**Comment by abellee** [comment]
has the swift sdk done?

**Comment by brototyp** [comment]
Hello @abellee, thanks for your message. The swift sdk is not ready yet. With the latest merged pull request in the 'swift3' branch it is possible to send the first analytics data. Once we have the basic metrics (i guess views and events), we will release a first version and add features with incremental updates.

**Comment by abellee** [comment]
@brototyp 
so happy to hear that. so when will you release the first version?

**Comment by brototyp** [comment]
@abellee Its hard to anticipate (as you see with the current *Swift 3 Rewrite* Milestone) because we are just a very small team involved in the process now. I don't want to make any promise, but I hope we will have a first version in about two weeks.

**Comment by abellee** [comment]
@brototyp 
ok, bravo!

**Comment by brototyp** [comment]
@abellee You are very welcome to join us. We are still looking for everyone who wants to be involved in adding features, reviewing code, writing documentation or just testing.

**Comment by abellee** [comment]
@brototyp I have no so much time to help you guys to improve features, but I can use this lib in our products to make testing, and I will post all my problems.

**Comment by brototyp** [comment]
@abellee Sounds great, thanks!

**Comment by brototyp** [comment]
Hey @abellee, I just merged the PiwikSDK 4.0.0-alpha1 branch. Please have a look at the [readme](https://github.com/piwik/piwik-sdk-ios/blob/swift3/README.md) and try it out. I will not be able to be very active in the next ~3 weeks. But please let us know if there are any issues and what features you want to see implemented next.

**Comment by abellee** [comment]
@brototyp I use the `pod 'PiwikTracker', branch: 'swift3'` in my podfile, and then `pod install`, but the pod shows me `[!] Unknown external source parameters for `PiwikTracker`: `{:branch=>"swift3"}``

**Comment by abellee** [comment]
@brototyp finally, I only have to add the files manually

**Comment by brototyp** [comment]
@abellee That was my fault. If you want to define a specific branch in a Podfile, one also has to define the repository. `pod 'PiwikTracker', git: 'https://github.com/piwik/piwik-sdk-ios.git', branch: 'swift3'`
Fixed it in the readme as well.

Did you find any issues or things that can be improved?
