### ISSUE TITLE
app crash in this sdk

### ISSUE THREAD

**Issue by YYDD** [piwik/piwik-sdk-ios#130]
Hi~
I found the crash in umeng(a third-part statistics platform)
*** -[NSDictionary initWithObjects:forKeys:]: count of objects (18) differs from count of keys (0)

when i locate the crash 
it occured in the method below:
__copy_helper_block_.855 (in LaoBaiStore) (PiwikTracker.m:1488)
__48-[PiwikTracker eventsFromStore:completionBlock:]_block_invoke (PiwikTracker.m:1497)

Could you check it and fix it.
Thanks!

**Comment by YYDD** [comment]
I found all the crashs happened in one user. So Does the user do something that creating some dirty data?

**Comment by brototyp** [comment]
Hi @YYDD, thanks for the crash report. It does sound like some corrupted data. Is there a symbolicated crashreport you can attach?

**Comment by brototyp** [comment]
Closing this for now. Feel free to reopen if you have more information on this topic.
