### ISSUE TITLE
macOS and tvOS support

### ISSUE THREAD

**Issue by brototyp** [piwik/piwik-sdk-ios#134]
I am not sure about the current state of macOS and tvOS support.

- Configure the Framework to be a universal framework
- Configure the Rakefile to run the tests for the macOS and tvOS platforms as well

**Comment by Sushhi** [comment]
Hi,

I'd like to use Piwik for a Apple TV app. Is there any news about the tvOS support ?

Regards,

**Comment by brototyp** [comment]
Hi @Sushhi,

I have started to look into it but I am not as far as to give an estimation. There are a few dependencies that I have to sort out. I will update here, once I have more information.

Help is always appreciated. :)

**Comment by brototyp** [comment]
This is now implemented and will be released with the next version.
