### ISSUE TITLE
can't use event Click on oc

### ISSUE THREAD

**Issue by HelloWorldStap** [piwik/piwik-sdk-ios#142]
can't use event Click on oc.........i can't  find   a  SEL  in  Tracker  about  event

**Comment by brototyp** [comment]
Hi @HelloWorldStap, do you mean calling the SDK with Objective-C code?

**Comment by brototyp** [comment]
If that is the case please try the following:

- Import the PiwikTracker Framework in the header of the file you want to use it in like so: `@import PiwikTracker;`
- Track your events like this for example: `[[Tracker shared] trackWithView:@[@"example"]];`

Does that work for you?

**Comment by HelloWorldStap** [comment]
i'am using  the newest beta  version  4.0.0-beta1  but  i can't find  the    Tracker.shared?.track(eventWithCategory: "player", action: "slide", name: "volume", value: 35.1)   using   Objective-C

**Comment by brototyp** [comment]
Hi @HelloWorldStap, thank you for your followup. I found the issue and fixed it in a pull request. I expect to release 4.0.0-beta2 in the end of this week where this fix should be included.
