### ISSUE TITLE
crash in 3.3.0

### ISSUE THREAD

**Issue by HelloWorldStap** [piwik/piwik-sdk-ios#143]
NSURL *modelURL = [[NSBundle mainBundle] URLForResource:@"piwiktracker" withExtension:@"momd"];
  the modelURl  is nil  in 3.3.0   
my progect  using   OC

**Comment by brototyp** [comment]
Hi @HelloWorldStap, thank you for your bug report. Can you give me some more inside on the crash? Do you have a crash report? Please check the [Contributing Guidelines](https://github.com/piwik/piwik-sdk-ios/blob/develop/CONTRIBUTING.md#reporting-bugs) to see a list of information that will help us help you.

**Comment by luohui8891** [comment]
Hmm, @brototyp face the same issue when I used `3.3.0` in my project. 
Seem the reason is that the core data resource haven't been copied to main bundle.

**Comment by brototyp** [comment]
Hi @HelloWorldStap, Hi @luohui8891, thank you both for your feedback. I've just seen that a fix was implemented in this commit: https://github.com/piwik/piwik-sdk-ios/commit/139d573808298222c01aed61396bc2d8b909b9d1

It was just not released yet. Can you do me a favor and try out the Piwik SDK from this exact branch and get back to me?

`pod 'PiwikTracker', :git => 'https://github.com/piwik/piwik-sdk-ios.git', :commit => '139d573808298222c01aed61396bc2d8b909b9d1'`

**Comment by luohui8891** [comment]
@brototyp I have upgraded it to 4.0 (Swift 3) and it works fine.

**Comment by YvesCandel** [comment]
I tested that specific commit and it seemed to work fine!

**Comment by brototyp** [comment]
Hi @luohui8891, Hi @YvesCandel, thank you both for you feedback. I will release a new patch for the Piwik SDK Version 3 so it is not necessary to reference the commit directly. I will post here, once it's done.
