### ISSUE TITLE
Renaming the Tracker class to PiwikTracker?

### ISSUE THREAD

**Issue by brototyp** [piwik/piwik-sdk-ios#146]
I just noticed the inconsistency that the main class that is used is named Tracker. The SDK is named PiwikTracker in the import as well as the cocoapod and many other places.

I think it would be best to rename the Tracker class to PiwikTracker.

**Comment by thorstenstark** [comment]
Yeah, I agree that renaming it to `PiwikTracker` would be a good idea. Just `Tracker` makes it also hard for others reading the code to recognise it as the piwik tracker instead of some other tracker.
