### ISSUE TITLE
See screen sizes in piwik backend

### ISSUE THREAD

**Issue by thorstenstark** [piwik/piwik-sdk-ios#149]
I think it would be useful to see the screen size of the tracked devices in the piwik backend. Currently there is only one screen size called "unknown".

**Comment by brototyp** [comment]
That is an easy thing to implement. In [this](https://developer.piwik.org/api-reference/tracking-api) document the **res** parameter is described as: _The resolution of the device the visitor is using, eg 1280x1024._

I think it is save to say that that the resolution of a device never changes so we don't need to save the resolution for every event, but rather send it along. I think the best thing would be to have them as properties of the Event struct but don't implement them with the need to set it externally. Something like `let screenSize = Device.makeCurrentDevice().screenSize`. The other thing then would be to encode the size in the `Event`s [queryItems](https://github.com/piwik/piwik-sdk-ios/blob/develop/PiwikTracker/URLSessionDispatcher.swift#L71) which encodes an event into an array of URLQueryItem.

**Comment by akshaykolte** [comment]
Assign this to me. I'll try working on it over the week.

**Comment by brototyp** [comment]
There is no need to assign issues. I am looking forward to you pull request. If you want to bounce ideas back and fourth just let me know.

**Comment by akshaykolte** [comment]
Can you let me know how to test the app, I pulled upstream from develop.
The build succeeds, but the tests dont work. Do I need to change targets in
project settings? How do I know if I add a parameter to to the Event struct
is reflecting while creating the url for the server.

Thanks.

**Comment by akshaykolte** [comment]
Got my tests to run. Had an issue with pods. Made change in Tests. A file was using Tracker instead of PiwikTracker. Tests ran successfully. Still can run the Example.

**Comment by brototyp** [comment]
Hi @akshaykolte thank you for your PR. I just checked about the Example application. There is the same issue like in the Tests. It's a merge issue. The example application should work, if you edit the `OptOutViewController.swift` and replace all `Tracker` with `PiwikTracker`. Sorry for that!
