### ISSUE TITLE
Get the different device names in the backend

### ISSUE THREAD

**Issue by thorstenstark** [piwik/piwik-sdk-ios#150]
It would be nice to see the names of the used iOS devices in the analytics. Currently it only says `iPhone` for all iPhone models including the simulator.

**Comment by brototyp** [comment]
The current information displayed in the Piwik Backend is read from the UserAgent. Setting more specific information (e.g. the specific device model) is not a normal thing for the user agent and, as far as I know, not supported by the Piwik Backend.

But, there is a way to get more information about the devices your users are using. Imho the best way would be to use [Custom Dimensions](https://github.com/piwik/piwik-sdk-ios/issues/111). Custom Dimensions are currently in development. Once it's implemented and merged the way to use would be similar to [this](https://github.com/piwik/piwik-sdk-ios/blob/d3fc4a3d9f57da8b34e820a27685f55b0bc3b775/Example/iOS%20Example/CustomDimensionsViewController.swift).
