### ISSUE TITLE
Setting a custom tracking api parameter

### ISSUE THREAD

**Issue by mattab** [piwik/piwik-sdk-ios#153]
Sometimes, new Piwik core releases or even any new plugin may add new parameters to the Tracking API. In those cases it is often not possible to make changes to all necessary SDKs, so the idea is to let user customise the tracking URL. 

-> It would be great to have such a method in 4.0.0 beta :+1: 

Fyi in the PHP SDK we have implemented the following:

```php

    /**
     * Sets a custom tracking parameter. This is useful if you need to send any tracking parameters for a 3rd party
     * plugin that is not shipped with Piwik itself. Please note that custom parameters are cleared after each
     * tracking request.
     *
     * @param string $trackingApiParameter The name of the tracking API parameter, eg 'dimension1'
     * @param string $value Tracking parameter value that shall be sent for this tracking parameter.
     * @return $this
     * @throws Exception
     */
    public function setCustomTrackingParameter($trackingApiParameter, $value)
    {
        $this->customParameters[$trackingApiParameter] = $value;
        return $this;
    }

```
For example users may want to override the Geo location info of country, region and city of a visitor (see https://github.com/piwik/piwik/issues/11563#issuecomment-304547116 for more info how to achieve this without having to set the token_auth)

refs https://github.com/piwik/piwik-sdk-ios/issues/82#issuecomment-161749201

**Comment by brototyp** [comment]
I think the best idea would be a combination of the following two features:

* Add a `let customTrackingParameters: [String:String]` to the Event object
* Make the `queue(event: )` of the `PiwikTracker` public

This way one could create a custom `Event` object, setting all existing parameters. The `customTrackingParameters` dictionary would then enable setting all the different parameters.

**Comment by mattab** [comment]
Is your `Event` related to Piwik Events? http://piwik.org/docs/event-tracking/

maybe it's possible to make it simpler and just have one method like in the PHP tracker, that will set the custom tracking parameter. Similar to 'setResolution', 'setUserId' etc

**Comment by brototyp** [comment]
Events in this SDK are rather "things that should be tracked". So an event could be a view, a download, an exception and so on. Those events are quite atomically. There is barely a situation where one would set any data on the Tracker class directly. In the iOS SDK you create an event and dispatch it via the tracker. There are shortcuts on the Tracker, like `track(view: )` but internally they just create an Event and then dispatch it via itself.

**Comment by mattab** [comment]
Hi @brototyp do you think it would be possible to prioritise this little feature? It would be awesome to have as it would let anyone track the not-yet-supported-by-SDK features, such as Media Analytics requests: https://developer.piwik.org/guides/media-analytics/custom-player#media-analytics-http-tracking-api-reference
Thanks for consideration!

**Comment by brototyp** [comment]
Hi @mattab, yes I will try to do that. Thanks for nudging. It takes a while to figure out this feature without exposing to much internals, and thus have to guarantee that they don't change soon.

**Comment by brototyp** [comment]
Good news! It just got merged to the development branch and will be part of the next release. Please check [this](https://github.com/piwik/piwik-sdk-ios#sending-custom-events) part of the readme for more details.
