### ISSUE TITLE
Crash in 4.0.0

### ISSUE THREAD

**Issue by luohui8891** [piwik/piwik-sdk-ios#162]
Hi we integrated Piwik 4.0.0 in our Application and released last week.
We found some crash [reports](http://crashes.to/s/dc292f147e2) in Fabric.
I reviewed my code and no idea about this report.

Here is the code of initialization. 
>let baseURL = URL(string: "https://_myhost_/piwik.php")
        self.tracker = PiwikTracker(siteId: piwikID, baseURL: baseURL!)

Any suggestion?

**Comment by brototyp** [comment]
Hi @luohui8891, thank you for the bug report. Unfortunately I wasn't able to reproduce your issue. Can you give me more information on how to reproduce it? Maybe some context? Is there event a little example application that reproduces this issue regularly?

**Comment by luohui8891** [comment]
Hi @brototyp , no more information about this issue, I just got it from Fabric.
Also I can't reproduce it in my side.
The only information I got is the crash stack.

BTW, just asking, do you know why the stack of PiwikTracker looks like this in Fabric?
![image](https://user-images.githubusercontent.com/1223339/28056834-f42c392e-6650-11e7-820a-a7f4be789178.png)
![image](https://user-images.githubusercontent.com/1223339/28059017-591bd606-6655-11e7-94fb-cbbb533798cc.png)

**Comment by luohui8891** [comment]
Hey, I also found a point maybe help in Fabric.
I reviewed the user crash reports, the stack are different between iOS 10.3.2 and iOS 10.0.x
Here is stack of iOS 10.3.2
![image](https://user-images.githubusercontent.com/1223339/28059397-bd49a67a-6656-11e7-8a51-127a569285b1.png)
Here is stack of iOS 10.0.2
![fabric](https://user-images.githubusercontent.com/1223339/28059482-fc34552e-6656-11e7-9244-bd7bc2111175.png)

**Comment by brototyp** [comment]
Hi @luohui8891, thanks for the followup. I think both are different crashes. The original is related to the NSUserDefaults. I think I do have an idea on the reason. I will post here once I am sure. The "10.3.2" is unrelated to this issue, but is related to how we calculate the User Agent. Can you open a separate issue for the second one, so we can better track it?

**Comment by brototyp** [comment]
I think the NSUserDefaults crash is related to how we instantiate the Visitor and Session Objects. Do you think it is possible to try out [this](https://github.com/piwik/piwik-sdk-ios/tree/bugfix/162-nsuserdefaults-crash) branch and see if the crash is fixed? Unfortunately I wasn't able to reproduce it myself.

**Comment by luohui8891** [comment]
@brototyp thank you for reply. 
OK, I will try it in our next build.

**Comment by brototyp** [comment]
Hi @luohui8891 is there any update on this issue?

**Comment by luohui8891** [comment]
Sorry, we are still working on the build. Haven't release.

**Comment by luohui8891** [comment]
@brototyp hi, we released the new version with this [fix](https://github.com/piwik/piwik-sdk-ios/tree/bugfix/162-nsuserdefaults-crash) you mentioned.
Didn't see the crash issue on Fabric any more.
So we think it has been fixed. 
Now you can merge it to master.
Thank you.
