### ISSUE TITLE
Crash when calculated the User Agent.

### ISSUE THREAD

**Issue by luohui8891** [piwik/piwik-sdk-ios#166]
This is the crash stack which I mentioned in #162 
![image](https://user-images.githubusercontent.com/1223339/28059397-bd49a67a-6656-11e7-8a51-127a569285b1.png)

**Comment by brototyp** [comment]
Hi @luohui8891 do you think this issue is related to #174?

**Comment by luohui8891** [comment]
@brototyp I don't think so. You can see the attached image, it's already on main thread.

**Comment by brototyp** [comment]
Hey @luohui8891, after you released your new version have you encountered this issue again? I am still struggling to reproduce it.

**Comment by luohui8891** [comment]
@brototyp no, didn't see it in new version any more.

**Comment by brototyp** [comment]
I will close this issue for now. Feel free to reopen it, if you encounter this issue again.
