### ISSUE TITLE
Dispatch of Events/View only happens Once

### ISSUE THREAD

**Issue by jmoukel** [piwik/piwik-sdk-ios#167]
Hey guys,

It seems like the dispatch of events/views only happens once, and not every 30 seconds.

This is the **dispatch** function: 
```
public func dispatch()
{
    guard !isDispatching else {
            logger.verbose("PiwikTracker is already dispatching.")
            return
    }
    guard queue.eventCount > 0 else {
            logger.info("No need to dispatch. Dispatch queue is empty.")
            startDispatchTimer()
            return
    }
    logger.info("Start dispatching events")
    isDispatching = true
    dispatchBatch()
}
```

In the last line, the **dispatchBatch()** function gets called. The **dispatchBatch()** function just sends all the events/views in the queue and then do not call the **startDispatchTimer()** at all to schedule a new execution of the **dispatch()** function. So the subsequent events/views reported never get sent to the server.

**Comment by brototyp** [comment]
Hi @jmoukel, thank you for this awesome bug report and thanks for the effort you put into it. This is an ugly bug. I will fix it right away and will write a test that catches it.

**Comment by jmoukel** [comment]
No problem, thank **you**.

**Comment by brototyp** [comment]
Hi @jmoukel, i just created a Pull Request. Would you review it? It is #169

**Comment by jmoukel** [comment]
@brototyp not allowed do that man, sorry.

**Comment by brototyp** [comment]
Released in version 4.1.0

**Comment by jmoukel** [comment]
Hey man @brototyp, the problem persists.

Even though now **self.startDispatchTimer()** is being called inside **dispatchBatch()** when there're no more events to report, it's being called on a background thread. When you fire a timer on a background thread, it may never call its selector if this background thread terminates for some reason. That's exactly what happens to me.

The following is an extract of the **dispatchBatch()** function. The success param of the **self.dispatcher.send(...)** function is being called on a background thread.
```
self.dispatcher.send(events: events, success: {
     self.queue.remove(events: events, completion:  {
          self.logger.info("Dispatched batch of \(events.count) events.")
          self.dispatchBatch()
     })
}
```

**Comment by brototyp** [comment]
Hi @jmoukel, thanks for the followup. I will dig into it this weekend.

**Comment by brototyp** [comment]
Hi @jmoukel, I just had a look and could reproduce the issue. I think the best thing ist to just ensure the timer is dispatched in the main thread. The pull request is open. I will let you know once it is merged.

**Comment by brototyp** [comment]
@jmoukel As you noticed, the PR is merged now.
