### ISSUE TITLE
Support custom Visitor userId

### ISSUE THREAD

**Issue by niksawtschuk** [piwik/piwik-sdk-ios#180]
I noticed that in previous versions of the SDK, this was supported. In my project we are using the newest version to leverage Swift and the ability to set custom Dimensions, however we also need to be able to set the userId of the current Visitor as well. 

I can see that this feature is listed under the `ToDo` section of the README, so since I need this now, I am going to do it! I am creating this Issue as a means of both following the Contributing guidelines and also to create a discussion around this feature.

**Comment by brototyp** [comment]
@niksawtschuk Thanks for the ticket and the heads up! I am looking forward to your solution.
You will see some of it is already prepared. The `Visitor` for example already has a `userId` which, once it is set, will already be transmitted to the Piwik Backend.

**Comment by brototyp** [comment]
Since this one is implemented in #181 and will be part of the next release i close this Issue.
