### ISSUE TITLE
sendContentImpressionWithName

### ISSUE THREAD

**Issue by marcoiacobelli** [piwik/piwik-sdk-ios#182]
Hi,
any ideas about why after sendContentImpressionWithName in piwik pro i can see only 
"URL pagina non definita". (in english: url not defined)

**My code**
`[[PiwikTracker sharedInstance] sendContentImpressionWithName:@"MediaCenterContent" piece:self.selectedResource.nome target:[self.selectedResource.categoria uppercaseString]];`

**Official documentation example (from PiwikTrackeriOSDemo)**
` [[PiwikTracker sharedInstance] sendContentImpressionWithName:@"DN" piece:@"dn_image.png" target:@"http://dn.se"];`

`  [[PiwikTracker sharedInstance] sendContentInteractionWithName:@"DN" piece:@"dn_image.png" target:@"http://dn.se"];`
 

tnx, 
any suggestions are welcome

**Comment by brototyp** [comment]
Hi @marcoiacobelli, can you attach a screenshot of what you are seeing in the Piwik Backed?

**Comment by brototyp** [comment]
Closing this for now. Please get in touch if you still have issues.
