### ISSUE TITLE
Can't install with Carthage.

### ISSUE THREAD

**Issue by thbaja** [piwik/piwik-sdk-ios#190]
When trying to install via Carthage I encounter this:
```
> carthage update
*** Fetching piwik-sdk-ios
*** Checking out piwik-sdk-ios at "v4.2.0"
Parse error: expected submodule commit SHA in output of task (ls-tree -z v4.2.0 AFNetworking) but encountered:
```

Cartfile:
```github "piwik/piwik-sdk-ios"```

**Comment by brototyp** [comment]
Hi @thbaja, thanks for the report. Is there more information after the `encountered:`?

**Comment by thbaja** [comment]
No, unfortunately not.
It seems that submodules can sometimes cause issues: https://github.com/Carthage/Carthage/issues/135

**Comment by brototyp** [comment]
Hi @thbaja, that was a good point. There was an old Submodule configured in the repository. I just deleted it and released it along with version 4.3.

**Comment by elitalon** [comment]
@thbaja Did this happen because you also had AFNetworking as a dependency or it just happens in general when installing piwik-sdk-ios with Carthage? The latter should've been caught when running `build_with_package_manager ` in the CI 🤔

**Comment by brototyp** [comment]
@elitalon I tested this issue yesterday by creating a new, empty Xcode project and adding the `github "piwik/piwik-sdk-ios"` to a Cartfile. So no other dependencies were necessary. Is this possibly an issue with just Xcode 9?

**Comment by brototyp** [comment]
I just checked. Travis is testing on Xcode 9, so it can't be it.
