### ISSUE TITLE
Add auto-url-generation

### ISSUE THREAD

**Issue by brototyp** [piwik/piwik-sdk-ios#197]
## Proposal:

- Add a new property contentBaseUrl to the PiwikTracker
- If this property is set, every event that has no url set will generate one by its own
- To generate a url, it will use the contentBaseUrl and append the action-array as path

## Example:

- contentBaseUrl is https://piwik.org
- actions is ["docs", "requirements"]
- the url will be https://piwik.org/docs/requirements

**Comment by brototyp** [comment]
After a bit debugging I figured that though the url is an optional in the API, it is basically non-optional for page views, since most features rely on the url instead of the actions (which I thought).

What does the user loose without the url for page views:
- The Visitor Log lacks the list of pages
- Actions -> Pages lack the list of pages
- Actions -> Entry pages and Exit pages are empty

Because of that, I think the `contentBaseUrl` should not be nil per default, but rather `http://<app-id>` per default and still be overridable for custom urls. Any objections?

**Comment by thbaja** [comment]
I think we should use it for all events. Currently I'm wrapping the piwik call in order to always set the url, both for page-views and actions. This makes it easier to compare web and app behaviour as well as monitor total usage.

**Comment by brototyp** [comment]
Sounds like a great plan. So like this?

- `contentBaseUrl` is per default derived from the App id
- If one doesn't want to auto-create any url, it is possible to set the `contentBaseUrl` to nil
- If one want to define the url on a per Event level, it overrides automatic created urls

**Comment by thbaja** [comment]
Sounds good. That way we give sufficient flexibility to handle all the use-cases I can think of (off the top of my head) .

**Comment by brototyp** [comment]
I just checked the Android sdk on how the contentBase is generated there and copied it [see](https://github.com/piwik/piwik-sdk-android/blob/master/piwik-sdk/src/main/java/org/piwik/sdk/Tracker.java#L522).

**Comment by brototyp** [comment]
Just released [version 4.4.0](https://github.com/piwik/piwik-sdk-ios/releases/tag/v4.4.0) containing this feature.
