### ISSUE TITLE
Tracking of device typ, iOS version, app version etc

### ISSUE THREAD

**Issue by flaushi** [piwik/piwik-sdk-ios#207]
Hi!
I wonder if there is a standardized way to collect statistical dimensions such as iOS version, device type (iPhone vs. iPad at least), device locale, and so on? If not, wouldn't it make sense to include this just directly in the tracker initialization code?
Maybe this is already the case but I could not find it?
Thanks in advance!
Oliver

**Comment by brototyp** [comment]
Hi @flaushi, unfortunately there is no such way, as there is no standardized way to record those values in the backend.
Some values are automatically recorded by analyzing the default User Agent (unless you changed it). Additional values can be configured as Custom Dimensions on the Backend side an can then be manually set in the app. More info [here](https://github.com/piwik/piwik-sdk-ios#custom-dimension)
