### ISSUE TITLE
Analytics not reflecting on Dashboard

### ISSUE THREAD

**Issue by ravinderpoonia07** [piwik/piwik-sdk-ios#213]
Hi Team,
We are using piwik to capture analytics, on Android and web everything is fine but on iOS analytics not getting reflecting on dashboard. Even on sample app i am not able to see analytics at dashboard. After going through old issues i came to know that if debug mode is on than it wouldn't show on dashboard, but in latest swift release i am not getting any option to disable debug mode. Please let me know is it a bug or i am missing something in implementation.

**Comment by brototyp** [comment]
Hi @ravinderpoonia07, is it possible that you have filtered out the current day? If i recall correctly the Backend shows per default 14 days up until yesterday. So if you are trying to display data for the current day it is filtered out.

**Comment by brototyp** [comment]
Closing it for now. Please get in touch again if you still have issues.
