### ISSUE TITLE
pod 'MatomoTracker', '~> 5.0' not working

### ISSUE THREAD

**Issue by ghost** [piwik/piwik-sdk-ios#232]
I had to add  pod 'MatomoTracker', '~> 5.0.0-beta1' to make it work.

**Comment by brototyp** [comment]
Hi @rveringa, did you try a `pod repo update`? The CocoaPods repository lists the 5.0.0 version. See [here](https://cocoapods.org/?q=matomo)

**Comment by ghost** [comment]
This was indeed the problem. Sorry for noobing

**Comment by brototyp** [comment]
No worries. Everyone does that from time to time!
