### ISSUE TITLE
Can we add automatic crash reporting to the SDK?

### ISSUE THREAD

**Issue by satheeshwaran** [piwik/piwik-sdk-ios#233]
Hello Guys,

We have been using Piwik SDKs for our apps and it is really great. How about adding automatic crash reporting in the SDK? Most of the analytics SDK's do the same and it would be really great if we add this in conjunction with event tracking. Any exception can be tracked with its preceding set of events that lead to the crash, Firebase crash reporting does a good job in this case. Let me know if this is something you are interested in so I can contribute.

**Comment by brototyp** [comment]
Hi @satheeshwaran, thanks for your feedback. I am happy that you like the SDK.

About your Idea. We actually already had an issue about that (see #18) and closed it, because I think the backend does not really support crash reports. I am currently talking with the backend team if there is such a feature that I overlooked. I will be back in touch with you once I have more information on that.

**Comment by brototyp** [comment]
Hi @satheeshwaran, I just got answers from the backend team. There currently is no support for that. Right now you could try two things:

- Create an event whenever you see there is a crash. This way you could count crashes or such. But you will not have a symbolicated stack trace.
- Use another tool for your crash reports. Like Fabric (former Crashlytics), Hockey, Sentry, ...

**Comment by satheeshwaran** [comment]
@brototyp  Thanks for getting back soon. I am already using other tools to track crashes but I would love to build something for Piwik & the open source community. Can we report it as a crash event for now and also attach stack trace? with minimal backend changes?

**Comment by brototyp** [comment]
@satheeshwaran Sorry for not responding. When I checked with the Backend team they said we would need a plugin on backend side to handle that. If you want to provide a plugin for that please get in touch with the backend team over here: https://github.com/matomo-org/matomo

One important question to solve in this case is the crash report symbolication which is usually done by most of the tools on the backend. If you want to do that in your plugin, you would have to upload the dSYM files for every build, which might be a little hassle to do every time. Let me know if there is anything I can help you with.

**Comment by samtuke** [comment]
FYI we're also interested in this feature, for both web app and native mobile apps

**Comment by JMCPH** [comment]
Is this implemented yet? We would love to use Matomo, but need this feature :)

**Comment by brototyp** [comment]
I don't think this is implemented. Things might have gotten a little bit simpler in the meantime with a few MetricKit additions in iOS 14, but it's still not super simple. 
I am open for any discussion on possible approaches.
