### ISSUE TITLE
Missing minimum deployment target settings in Xcode project

### ISSUE THREAD

**Issue by ghost** [piwik/piwik-sdk-ios#238]
### What happened
We are using Matomo in a project, which has an iOS and tvOS application. While on iOS everything is fine, I permanently ran into an issue on tvOS when importing the `MatomoTracker` module. Xcode throws an error:

<img width="776" alt="screenshot 2018-04-25 at 16 57 10" src="https://user-images.githubusercontent.com/871198/39259890-f411967e-48b7-11e8-9c1d-a27046846bd3.png">

### What I've done
Our project needs support for tvOS 10.1. So I tweaked carthage's checkouts by setting the missing deployment target values for tvOS (to 10.0), built the modules again and everything worked as expected.

#### Before Change

<img width="1354" alt="beforechange" src="https://user-images.githubusercontent.com/871198/39267410-01fa0978-48cd-11e8-95ec-c40fbe46aa69.png">

You can see, the minimum deployment target settings for tvOS, watchOS and macOS are missing. In this case Xcode just uses the latest version for each platform.

#### After Change

<img width="1354" alt="afterchange" src="https://user-images.githubusercontent.com/871198/39267418-0b5a4fbe-48cd-11e8-887f-fb9bb7a83746.png">

### Conclusion
This project should be updated **asap** (current situation is a *no-go* for us!) with valid deployment target settings for all platforms (or dedicated targets for each platform). If you agree, I can make the changes and will open a pull request than.

**Comment by ghost** [comment]
@brototyp I think this issue has to be classified as important (speaking as a carthage user)!

**Comment by brototyp** [comment]
Hi @phranck, thanks a lot for your suggestion in this case. As I am not a heavy Carthage user, I wasn't aware of the misconfiguration in this case. Cocoapods uses the Podspec to define the Deployment Target.
A pull request would be awesome!
