### ISSUE TITLE
 linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by luangaolei** [piwik/piwik-sdk-ios#243]
Error reporting in import project:   linker command failed with exit code 1 (use -v to see invocation)

MatomoTracker

**Comment by brototyp** [comment]
Hi @luangaolei, thanks for your report. Can you please [describe your issue and go a bit more into detail](https://github.com/matomo-org/matomo-sdk-ios/blob/develop/CONTRIBUTING.md#reporting-bugs)?

**Comment by luangaolei** [comment]
Hi  @brototyp , Before our project, we had AFNetWorking and sdwebimage and so on. When I used cocoapods to import matomo, the compilation project would report this error.
My solution now is to delete all of the target-building Setting - Other Linker flags, leaving only "$(inherited)", which will resolve the error.
Will this solution have any impact?

**Comment by luangaolei** [comment]
@brototyp  There is also a question, how can I statistical the jump between pages?

**Comment by brototyp** [comment]
Hi @luangaolei, for the Matomo SDK this should not have any negative impact. But I cannot give you any advice to your project as it depends on what your project uses and needs.

> There is also a question, how can I statistical the jump between pages?

What do you mean by that?

**Comment by luangaolei** [comment]
@brototyp Hi, Now the general statistics SDK will default to the jump between the pages, such as UMeng statistics.
For example, I want to know the number of jumps from page1 to page2.
Do I need to do something special or Matomo will automatically count? if Matomo automatically statistics, where do I see the data?

**Comment by brototyp** [comment]
Hi @luangaolei, the SDK does not track anything by default. Please refer to the [README](https://github.com/matomo-org/matomo-sdk-ios#usage) how to use the SDK and to the [Matomo website](https://matomo.org/features/) to learn how to interpret the tracked data.
