### ISSUE TITLE
Readme improvements

### ISSUE THREAD

**Issue by briomusic** [piwik/piwik-sdk-ios#246]
1. Many other frameworks (e.g. AFNetworking) describe the whole process to go through using cocoapods and carthage, including installation of the managers themselves as well as an example for an entire Podfile. Maybe this is something worth looking into four our readme?
2. The line about requirement to “import Matomotracker” belongs in ‘Usage’ as it applies to both, Cocoapods and Carthage.
3. The tracker used in the readme (and the ios example app) is “demo2.matomo.org”. I assume this is a public tracker with everyones tracked events on it. Still, is there any way to look at the events I am creating to confirm my installation is working?
4. Alternatively, Matomo now offer a free and easy way to create your own cloud server instance under this link: https://www.innocraft.cloud/start-30-day-free-analytics-trial
5. Maybe it would be worth mentioning this in the readme? (Danger of having a dead link in the readme if they decide to change the link in the future)

I am new to the project by invitation from @brototyp please do let me know if the format of my issues is correct or if I should split this into several issues.

**Comment by brototyp** [comment]
Hi @briomusic, thanks a lot for your ideas here!

> 1. Many other frameworks (e.g. AFNetworking) describe the whole process to go through using cocoapods and carthage, including installation of the managers themselves as well as an example for an entire Podfile. Maybe this is something worth looking into four our readme?

Currently I feel like our main README is getting a little bit to big. What do you think about adding a more verbose "Getting Started" guide in the wiki and linking to it from the Readme? So we have the barebone basics in the README and all the details in another document.

> 2. The line about requirement to “import Matomotracker” belongs in ‘Usage’ as it applies to both, Cocoapods and Carthage.

That's true. Let's change that.

> 3. The tracker used in the readme (and the ios example app) is “demo2.matomo.org”. I assume this is a public tracker with everyones tracked events on it. Still, is there any way to look at the events I am creating to confirm my installation is working?

Let's see what is happening in #247 and change it if possible.

> 4. Alternatively, Matomo now offer a free and easy way to create your own cloud server instance under this link: https://www.innocraft.cloud/start-30-day-free-analytics-trial
Maybe it would be worth mentioning this in the readme? (Danger of having a dead link in the readme if they decide to change the link in the future)

There are a few important things here:

- The link is not actually something that Matomo provides, but a company called innocraft (that is very close to Matomo).
- Under that link you can actually create a free trial, but not an actually free instance to use (as long as you want).

Maybe we can add (or link to) a document that helps the user to decide on their backend options. Either buy a hosted one or download the Matomo backend and host an own one.

> I am new to the project by invitation from @brototyp please do let me know if the format of my issues is correct or if I should split this into several issues.

Awesome! Welcome to the project.
