### ISSUE TITLE
Tracker configuration in the iOS example app

### ISSUE THREAD

**Issue by briomusic** [piwik/piwik-sdk-ios#247]
The tracker used in the ios example app is “demo2.matomo.org”. I am not sure if data tracked to this address can be viewed or retrieved?
The tracker URL that can be entered through the Configuration Screen is stored to user defaults and ignored. This screen should display the default tracker (and site id) and allow to change it.

**Comment by brototyp** [comment]
Hi @briomusic, thanks a lot for your suggestion.

The demo2.matomo.org is actually not a public instance. I agree with you that it would be nice for a developer of the SDK or one that simply wants to try out the SDK to be able to see what is tracked.

I am currently discussing with the backend team if it is possible to track to demo.matomo.org which is a public backend. I will get back to you once I have that information.

**Comment by brototyp** [comment]
Hi @briomusic, I have great news. The [demo2.matomo.org](https://demo2.matomo.org/) now shows tracked data without the need to log in. I think this way we should simply remove the options on the Configuration screen and document that you can inspect the tracked data on the server. What do you think about that?

**Comment by briomusic** [comment]
How can you view the data that is tracked to demo2.matomo.org?
As an alternative to your suggestion, we could have demo2.matomo.org appear on the Configuration screen by default, and allow the user to change it from there (if, for example, they signed up for a free trial elsewhere).

**Comment by brototyp** [comment]
> How can you view the data that is tracked to demo2.matomo.org?

Just go to that website. It is now publicly available.

> As an alternative to your suggestion, we could have demo2.matomo.org appear on the Configuration screen by default, and allow the user to change it from there (if, for example, they signed up for a free trial elsewhere).

I would rather not do that, since the SDK isn't designed to work this way and it isn't a thing that the SDK has to support.
