### ISSUE TITLE
Query visit information

### ISSUE THREAD

**Issue by elkorb** [piwik/piwik-sdk-ios#252]
Hi @brototyp ,
Is there any way to query visit information (e.g. config_pdf, config_quicktime etc.)?
Thanks.

**Comment by brototyp** [comment]
Hi @elkorb, thanks for getting in touch and sorry for me not responding in a while.
Unfortunately I am not totally sure what your question is. Are these (e.g. config_pdf, config_quicktime etc.) values that you recorded using the SDK? If so, how did you record these?

**Comment by brototyp** [comment]
I am closing this issue for now. Feel free to reopen it if you think it is necessary.
