### ISSUE TITLE
 Replaced generic phone model by device model 

### ISSUE THREAD

**Issue by Pe-te** [piwik/piwik-sdk-ios#254]
For android devices we see the specific device model in the backend, for iOS devices we only see generic "iPad" or "iPhone".
In pull request #253 we replace the generic string in the user agent with the real device model (e.g. iPhone8,4), which lets the backend properly display "iPhone SE".

Works for us now, but is it a good approach or do we have a bug in our code somewhere?

**Comment by brototyp** [comment]
This issue got merged and will be part of the next release. Thanks a lot @Pe-te 

General Note: [This FAQ](https://github.com/matomo-org/matomo-sdk-ios/wiki/FAQ#in-the-backend-devies-are-just-shown-as-apple-iphone-how-do-i-get-more-information-such-as-specific-device-or-os-version) needs to be updated before the release.

**Comment by brototyp** [comment]
This just got release as part of the 5.2 release.
