### ISSUE TITLE
Content Impressions / Content Interactions

### ISSUE THREAD

**Issue by kanjanaSi** [piwik/piwik-sdk-ios#255]
Do you have any plan to implement Content Impressions and Content Interactions?
Documentation: [https://matomo.org/docs/content-tracking/](url)
API: [https://developer.matomo.org/api-reference/content-tracking](url)

**Comment by brototyp** [comment]
This got implemented and will be part of the next release.

**Comment by brototyp** [comment]
Content tracking just got release as part of the 5.2 release.
