### ISSUE TITLE
Missing swift version in MatomoTracker.podspec

### ISSUE THREAD

**Issue by AbbyM** [piwik/piwik-sdk-ios#260]
Hello,

Swift version is missing from the pod spec.

Actually we have to set it manualy in "build settings" to make it work with objective-c project.

Adding " **s.swift_version = '4.1'** " to podspec will fix this!

![screen shot 2018-07-16 at 11 08 46](https://user-images.githubusercontent.com/2647931/42750767-b8e43e1e-88e8-11e8-8426-6f282fc31a62.png)
![screen shot 2018-07-16 at 11 10 59](https://user-images.githubusercontent.com/2647931/42750834-f948f0f8-88e8-11e8-89a4-8a22ecb80fd2.png)

**Comment by AbbyM** [comment]
Here is a hack to set swift version to 4.1 in pod file.

Add this to your podfile, this force the MatomoTracker sub specs to use swift version 4.1

    post_install do |installer|
        installer.pods_project.targets.each do |target|
            if ['MatomoTracker'].include? target.name
                target.build_configurations.each do |config|
                    config.build_settings['SWIFT_VERSION'] = '4.1'
                end
            end
        end
    end

**Comment by brototyp** [comment]
Oh, I wasn't aware of that. Interesting.
Do you have a clue, why that works in our iOS Example application with neither of those?

**Comment by AbbyM** [comment]
Yes, if you try your pod only in the example app project created with the pod library, the default swift is set to last swift version.

So no error,  but integrating the pod in a real project, pod is unable to set swift version.

I think trying pods in another project is a good practice to prevent that things.

You can do it easily with that kind of podfile :

    pod 'MatomoTracker', :path =>  "../MatomoTracker" // path to folder with matomo podspec

Hope it can help!

**Comment by brototyp** [comment]
Oh, I see. Since the Example project uses Swift 4.1 as well this version is used for the pod (if not defined otherwise). Thanks for the explanation!

I am open for a pull request in this regard.

**Comment by AbbyM** [comment]
@brototyp
Here it is!

**Comment by brototyp** [comment]
Thanks a lot. I just merged it. It will be part of the next release.
