### ISSUE TITLE
iOS App Implementation

### ISSUE THREAD

**Issue by avadhbambhroliya** [piwik/piwik-sdk-ios#264]
is there any easy way to implement in iOS App other than typing this line **matomoTracker.track(view: [“path”,“to”,“your”,“page”])** in every controller?

**Comment by ghost** [comment]
I also have same question..

**Comment by brototyp** [comment]
Sure, what do you have in mind? You could create a custom ViewController, add some implementation there and let all your ViewControllers inherit from this one.

```Swift

class MatomoTrackedViewController: UIViewController {

  var path: [String]? = nil

  func viewDidAppear(animated: Boolean) {
    super.viewDidAppear(animated: animated)
    matomoTracker.track(view: path)
  }
}
```

I wouldn't reccomend that, because you lose quite some flexibility.

**Comment by avadhbambhroliya** [comment]
Thank you @brototyp

**Comment by brototyp** [comment]
Absolutely. You are welcome!
