### ISSUE TITLE
Pod Installation isse

### ISSUE THREAD

**Issue by sarankumar291** [piwik/piwik-sdk-ios#265]
[!] Error installing MatomoTracker
[!] /usr/bin/git clone https://github.com/matomo-org/matomo-sdk-ios.git /var/folders/qq/ck1y6xp13c7c8ppp2_v3913c0000gp/T/d20180813-4685-ljthqr --template= --single-branch --depth 1 --branch v5.2.0

Cloning into '/var/folders/qq/ck1y6xp13c7c8ppp2_v3913c0000gp/T/d20180813-4685-ljthqr'...
fatal: unable to access 'https://github.com/matomo-org/matomo-sdk-ios.git/': Could not resolve host: github.com

**Comment by brototyp** [comment]
Hi @sarankumar291, thanks for your issue report. It looks like this was just an issue where GitHub was down. Please just try installing it again.
