### ISSUE TITLE
Add multiple custom variables to an event

### ISSUE THREAD

**Issue by danielceinos** [piwik/piwik-sdk-ios#269]
I've the requirement to add multiple variables for each single event, not in the global tracker instance parameters. I've tried with customTrackingParameter but it doesn't show up in our Matomo event tracker web.

**Comment by brototyp** [comment]
@danielceinos Thanks for your question. What is exactly your call that you are using? Are you using the `track(_ event: Event)` function? How are you generating your Event?

**Comment by danielceinos** [comment]
Hi,
I'm using this func to send an event:
```swift

func trackView (title: String, subsection1: String?, subsection2: String?) {
    let tracker = MatomoTracker.shared
    let event = Event(tracker: tracker, action: [title])
    tracker.track(event)
}
```
My problem I need to do something like this:

```swift
event.setCustomVariable(withIndex: 1, name: "subsection1", value: subsection1 ?? "")
event.setCustomVariable(withIndex: 2, name: "subsection2", value: subsection2 ?? "")
```

this function exists on MatomoTracker but not for the event.

**Comment by brototyp** [comment]
The `Event` constructor has some more optional parameter. One is `dimensions` and the other one is `variables`. Depending if you want to set a custom variable or a custom dimension you can use one of these to create an Event with specific custom variables or dimensions that are only valid for this event.

You could for example write such an extension: 

```Swift
extension MatomoTracker {
    func trackView(title: String, subsection1: String, subsection2: String) {
        let event = Event(tracker: self, action: [title], dimensions: [CustomDimension(index: 0, value: subsection1), CustomDimension(index: 1, value: subsection2)])
        track(event)
    }
}
```

As an alternative: There is already a function where you can pass in a view, an optional url and an array of dimensions: `public func track(view: [String], url: URL? = nil, dimensions: [CustomDimension] = [])`.

**Comment by brototyp** [comment]
Oh, I just saw, that you are talking about `variable` instead of `dimensions` and that the initializer of the `CustomVariable` is only internal. 

In this case I don't see any option. Setting the `variables` in the `customTrackingParameters` will not work, since it will be "overridden" by the variables set internally (even if they are empty). So I guess the only option here is to change the `CustomVariable` initializer to be public.

**Comment by danielceinos** [comment]
Yes, thats  my problem, I need to use `CustomVariable`.
How we proceed? Should I make a pull request for that? Do you prefer to do it yourself?
Thanks for your answers.

**Comment by brototyp** [comment]
It would be awesome if you could create a PR for that. I will happily review it. I am currently planning to create a new release on the weekend or beginning next week, so I guess that would help you. As an alternative you could reference the branch in the meantime.

**Comment by danielceinos** [comment]
Hi, I just tried adding a public init to `CustomVariable` , but when I send multiple events on the matomo tracking page only shows the custom variables for each  bunch of events instead for each event. I was searching and I found that replacing the api key `_cvar` with `cvar` sends custom variables for each individual event.

**Comment by brototyp** [comment]
Hm, interesting. Can you do me a favor and set the logger to verbose and check the logs if these "bunch of events" already have the `_cvar` set? Then we can see if this is a local issue or an issue of the interpretation of what we are sending.

`matomoTracker.logger = DefaultLogger(minLevel: .verbose)`

**Comment by brototyp** [comment]
This was just auto-closed by the merged pull request. I just reopened this until we solved this issue.

**Comment by danielceinos** [comment]
The logs rae fine, each event is send with his own custom variables. I'll search what's happening and come back with a solution.
Thanks.

**Comment by brototyp** [comment]
Hm, that is interesting. The iOS SDK sends events always in 20-events-batches. Is it possible that there is an issue where these 20 events always share the custom variables? Maybe try to (just for debug purposes) set the `private let numberOfEventsDispatchedAtOnce = 20` to 1 to see how that behaves? If that changes something I would try to get in touch with the Backend team.

Also maybe try to check the actual requests via Charles. (I don't think there is an issue, but you never know).

**Comment by brototyp** [comment]
Hi @danielceinos, is there any update on this issue? Did you resolve your problem?

**Comment by brototyp** [comment]
I will close this issue for now. Feel free to reopen it if needed.
