### ISSUE TITLE
Goal tracking

### ISSUE THREAD

**Issue by ThomasGoehringer** [piwik/piwik-sdk-ios#272]
I just migrated to the newest version and noticed that there is no goal tracking anymore. If there was no reason for removing it, shouldn't it be easy to implement it again?

**Comment by ThomasGoehringer** [comment]
I made an implementation myself. Should I make a PR?

**Comment by brototyp** [comment]
Hi @ThomasGoehringer, thanks a lot for getting in touch and asking about goal tracking. It just wasn't implemented in the Swift SDK yet. If you could create a PR that would be splendid!

**Comment by ThomasGoehringer** [comment]
Created a PR
#273

**Comment by brototyp** [comment]
The only thing left to do now is to add the Goal Tracking to the example application.

**Comment by brototyp** [comment]
This got implemented and will be part of the next release.
