### ISSUE TITLE
Can't call copyFromOldSharedInstance from Obj-C

### ISSUE THREAD

**Issue by fridtjof** [piwik/piwik-sdk-ios#282]
See https://github.com/vector-im/riot-ios/pull/2159

This could be fixed by adding an @objc annotation to the method.

**Comment by brototyp** [comment]
Hi @fridtjof, thanks for reporting this issue. If you wan't to I am open for a pull request in this regard 😊

**Comment by brototyp** [comment]
This got implemented by @fridtjof, merged and will be part of the next release.

**Comment by brototyp** [comment]
This was released in v6.0.1.
