### ISSUE TITLE
Does this project work with objective-c projects?

### ISSUE THREAD

**Issue by newmanw** [piwik/piwik-sdk-ios#284]
I see a reference to objective-c in the readme, however the instructions for use with an objective-c project don't exist.

At least for a cocoapods install it would be helpful to show how to import matamo files.

**Comment by brototyp** [comment]
Hey @newmanw, thanks for writing an issue. Yes there is basic objective-c support.

> however the instructions for use with an objective-c project don't exist.

Hm, that is weird. I just rechecked the link and it points to the FAQ talking about the objc support: https://github.com/matomo-org/matomo-sdk-ios/wiki/FAQ#how-to-use-the-matomotracker-from-objective-c

Is there anything in particular you would like to know, that isn't covered by that short FAQ entry?

**Comment by newmanw** [comment]
@brototyp thanks for the reply.  With that FAQ still having troubles.  I am able to add a swift file, verified that my version is 4.2.

However when I try to import:

<img width="832" alt="screen shot 2019-01-26 at 1 32 49 pm" src="https://user-images.githubusercontent.com/3382274/51792498-e98d9500-216e-11e9-82de-99e0917e1655.png">

I have deleted my xcworkspace and tried a pod install again with no luck.  Its a legacy objective-c project so could be something strange going on.

Here is my podfile:

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Matomo.Test' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Matomo.Test
  pod 'MatomoTracker', '~> 6'

end
```

Also I did verify that in my "Builld Settings" modules are enabled.

Any ideas?

**Comment by brototyp** [comment]
Hey @newmanw, thanks for your followup. I just tried to create a new objc project and import the Matomo Tracker. I encountered one issue. The FAQ states "Add a random .swift file to your project. You can delete if from the project right away." but for me it didn't work if I actually deleted the swift file afterwards. Maybe you can check that?

Here is a super fresh project that I created in this context.

[Test.zip](https://github.com/matomo-org/matomo-sdk-ios/files/2800214/Test.zip)

**Comment by brototyp** [comment]
I'll close this issue for now as it seems to be solved. Feel free to reopen if it still exists.
