### ISSUE TITLE
matomo.php vs piwik.php

### ISSUE THREAD

**Issue by oskitar89** [piwik/piwik-sdk-ios#285]
In the web site I don't receive any track. Appear this javascript code and it add matomo.php to the home web, but, in the library the website has to end with piwik.php. Any solution?

javascript

<script type="text/javascript">
  var _paq = window._paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="https://www.example.com/";
    _paq.push(['setTrackerUrl', u+'matomo.php']);
    _paq.push(['setSiteId', '32']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
  })();
</script>

mobile

@objc convenience public init(siteId: String, baseURL: URL, userAgent: String? = nil) {
        assert(baseURL.absoluteString.hasSuffix("piwik.php"), "The baseURL is expected to end in piwik.php")
        
        let queue = MemoryQueue()
        let dispatcher = URLSessionDispatcher(baseURL: baseURL, userAgent: userAgent)
        self.init(siteId: siteId, queue: queue, dispatcher: dispatcher)
    }

**Comment by brototyp** [comment]
Hi @oskitar89, thanks for creating this issue. Correct me if I am wrong, but as I understood it, you are currently initializing the `MatomoTracker` with a url ending in `matomo.php` but it is failing, because it requires a url ending in `piwik.php`.

If I am correct here, there are two things to do.
1. We should change the check, so that it checks for either of both.
2. In the meantime, you can just change your url in such a way that it ends in `piwik.php`. 

The backend now defaults to `matomo.php` but both work and always will.

**Comment by oskitar89** [comment]
It doesn’t work with matomo.php or piwik.php. We are seeing in the log that all of events are correctly sended. But at the end we are not receveing nothing on the website. What we can do?

**Comment by brototyp** [comment]
Is it possible, that you use a "wrong" filter on the website? If I recall correctly, per default it excludes today, which might lead to what you are seeing as "no events are received".

**Comment by oskitar89** [comment]
We created that site yesterday, so today we have to see the events from yesterday, right?
We have others sites created (all are web and not mobile) and are working correctly. Anything else we can do? And that “filter”, where I can find it? In order to change it?
Thanks

**Comment by brototyp** [comment]
I am not sure about what you have to see. Regarding the filter: It is just below the top navigationbar, right of where you select your website/app. There you can select a timespan.

<img width="686" alt="bildschirmfoto 2019-02-03 um 18 26 10" src="https://user-images.githubusercontent.com/113456/52180023-50e7bc80-27e1-11e9-9722-a3ef0e727252.png">

**Comment by oskitar89** [comment]
I dont' have this dashboard because I don't receive anything yet.

![captura-de-pantalla-2019-02-04-a-las-8 260](https://user-images.githubusercontent.com/5586013/52195803-b2e40880-2859-11e9-987b-1d45839f61e4.png)

**Comment by oskitar89** [comment]
Problem solved!! The general settings of matomo don't track our IP. We don't put the IP in this project but it used the general settings of matomo. Thanks

**Comment by brototyp** [comment]
Great. I am happy you solved your issue and thanks for the followup.
