### ISSUE TITLE
Remove assertion preventing initialization 

### ISSUE THREAD

**Issue by TheIronMarx** [piwik/piwik-sdk-ios#288]
As of Matomo SDK 6, the first line of the convenience initializer is the following assertion.
```
@objc convenience public init(siteId: String, baseURL: URL, userAgent: String? = nil) {
assert(baseURL.absoluteString.hasSuffix("piwik.php"), "The baseURL is expected to end in piwik.php")
// ...
}
```

On top of being out of date and incorrect, it seems like a really needless enforcement. At worst, maybe a warning or some other nonblocking logs to the console. Furthermore, this is immediately stopping me from continuing as our baseURL does not conclude with `piwik.php` but `matomo.php`.

Thoughts?

**Comment by brototyp** [comment]
Hi @TheIronMarx,

yes you are correct. That should be changed to also allow `matomo.php`. There was [a ticket](https://github.com/matomo-org/matomo-sdk-ios/issues/285#issuecomment-459670345) in this regard but it got closed.

I will accept PR's that change this. In the meantime you can simply change your baseURL to end on `piwik.php` instead of `matomo.php`. Both are supported.

**Comment by TheIronMarx** [comment]
Yeah I see that! Whew. I'll get to the PR later this week. 


Hopefully.


In the mean time, opinions on changing the assertion to a print out to the console?

**Comment by brototyp** [comment]
I don't think there is a reason to use a URL other than ending in either `matomo.php` or `piwik.php` or am I missing something here?

Changing it to just a log makes it far easier missable. If one misses that there is just no data in the backend at all. Having an assertion here will probably save many developers time debugging and me quite a bit time supporting.

Unless there is a strong reason to remove the assertion I guess I would keep it.

**Comment by TheIronMarx** [comment]
Alright. I suppose that's much more your call than mine. I'll include both in the PR.

**Comment by brototyp** [comment]
Oh man, super sorry about that. I already implemented the changes but never merged them. There is an open PR in this regard: #286. Looks like my brain isn't fully booted for the start of the week.

**Comment by brototyp** [comment]
I just merged that PR. It will be part of the next release.

**Comment by TheIronMarx** [comment]
Thank you!
