### ISSUE TITLE
Question: Support for Heatmap & Session Recording

### ISSUE THREAD

**Issue by denbue** [piwik/piwik-sdk-ios#290]
Hi,

Not sure if this is the right place to ask or if I need to check with the author of the plugin. But I was wondering if the SDK supports Heatmap & Session Recording ? 

https://plugins.matomo.org/HeatmapSessionRecording

Thanks!

**Comment by brototyp** [comment]
Hey @denbue, thanks for asking. This is definitely not a wrong place to ask this question.

Unfortunately, the SDK currently doesn't support this plugin. As to date, only the core functionality of Matomo is supported.

@mattab, do you know if there is a public API for this plugin that could be used by mobile apps?

**Comment by tsteur** [comment]
@brototyp there is an API to track data for this, but we wouldn't be able to show a heatmap or a recorded session as it's fully based on capturing the HTML which a mobile app doesn't have. So basically on a website we recorded the DOM structure, and when showing the heatmap or session we "replay" the DOM and its DOM changes.

**Comment by denbue** [comment]
Thanks for the insights. Based on that I assume this feature won't be supported for at least the foreseeable future?

**Comment by brototyp** [comment]
Thanks @tsteur for your insight.

That's true. Generating a DOM from an app is a major challenge. Even once you have a DOM there are additional challenges, such as images we would need to solve.
