### ISSUE TITLE
not found for architecture x86_64 in object-c project

### ISSUE THREAD

**Issue by shengliZh** [piwik/piwik-sdk-ios#293]

**Comment by brototyp** [comment]
Hi @shengliZh, thanks for your issue. Can you give us some detail? Possibly check our [guidelines for reporting a bug](https://github.com/matomo-org/matomo-sdk-ios/blob/develop/CONTRIBUTING.md#reporting-bugs).

**Comment by shengliZh** [comment]
already solved, thank you

**Comment by brototyp** [comment]
Great! Thanks for the followup! Enjoy Matomo and let us know if you encounter any other issue.
