### ISSUE TITLE
How to support the scope "page" via swift SDK.

### ISSUE THREAD

**Issue by lpz191** [piwik/piwik-sdk-ios#298]
I have used swift matomo SDK for a while, but I found the SDK only support the scope "visit" instead of scope "page". However, this SDK could support the scope "page" by android SDK or Javascript SDK. Please tell me how to support the scope "page" via swift SDK as soon as possible. Thank U!

- [ ]

**Comment by aaronliruns** [comment]
> The Matomo SDK currently supports Custom Dimensions for the Visit Scope.

I would like to ask the same. Is there any reason why the sdk doesn't support a narrower scope? we would like to track by view or page. How come its available in Android sdk then?

The sdk is supposed to be a client and actual tracking should be done on the server side, isn't it?

Looking forward to your reply.

**Comment by brototyp** [comment]
Hi @lpz191 and @aaronliruns, 

thanks for your questions. You can add `CustomDimensions` to every single event that you track.

Please have a look at these [track functions here](https://github.com/matomo-org/matomo-sdk-ios/blob/develop/MatomoTracker/MatomoTracker.swift#L273). The tracking functions for views and events have a `dimensions` parameter where you could add your dimensions for that specific view or event. On top of that, there is the generic track event function where you can pass your `Event` object which can be used to track all supported event types. The `trackGoal` and `trackOrder` function currently do not provide a parameter for custom dimensions.

I hope this helped.

**Comment by brototyp** [comment]
I'll close this for now. Please feel free to comment on this ticket if it didn't solve your problem.
