### ISSUE TITLE
How do I set different siteId based on configuration?

### ISSUE THREAD

**Issue by hardikamal** [piwik/piwik-sdk-ios#302]
Hi,

How do I set different siteId based on the configuration for example if I am on debug mode my siteId is 1 and if I am on staging mode my siteId is 2 and if I am on release mode my siteId is 3?

**Comment by brototyp** [comment]
Hi @hardikamal, thanks for your question.

I guess the best idea is to initialize your tracker differently based on your configuration. This then depends on the way your are defining your modes, but this could help:

```swift

#if Debug
    let matomoTracker = MatomoTracker(siteId: "1", baseURL: matomoUrl)
#elseif Staging
    let matomoTracker = MatomoTracker(siteId: "2", baseURL: matomoUrl)
#else
    let matomoTracker = MatomoTracker(siteId: "3", baseURL: matomoUrl)
#endif
```

**Comment by brototyp** [comment]
I'll close it for now. Please let me know if you have any other issue.
