### ISSUE TITLE
Swift 5.0 for Matomo iOS

### ISSUE THREAD

**Issue by hardikamal** [piwik/piwik-sdk-ios#307]
Hi, can you publish new version on Cocoapods with swift 5 support? Thanks

**Comment by simonnickel** [comment]
I created a PR for this: https://github.com/matomo-org/matomo-sdk-ios/pull/306

But the build fails in travis-ci. Seems to me like it is not up to date and does not support Swift 5.0.

Anyone here with access to update travis?

**Comment by brototyp** [comment]
Hey @simonnickel, thanks. I just replied to your PR.

**Comment by simonnickel** [comment]
Hey @brototyp thanks, it kind of worked. But tests are still failing in travis, not sure why though.

Maybe someone can help to figure this out?

**Comment by simonnickel** [comment]
Updated the PR and tests are running now. 

Had to disable iOS 9.3 and 8.4 though, see comments on https://github.com/matomo-org/matomo-sdk-ios/pull/306

**Comment by brototyp** [comment]
#306 Got merged. This will be part of the next release.
