### ISSUE TITLE
Incorrect percent encoding for "+" character

### ISSUE THREAD

**Issue by Megal** [piwik/piwik-sdk-ios#313]
### How to reproduce

Send an event with custom dimension that contains "+" characters in value.

### Expected result

Observe a same value as it was sent from device

### Actual result

Value doesn't contains any + characters.

### Affected version

Reproducible on version 7.0.0

### Possible solution:
https://stackoverflow.com/a/41568692/2798503

**Comment by brototyp** [comment]
This is released in v7.4
