### ISSUE TITLE
Changing the matomo tracker's siteID dynamic 

### ISSUE THREAD

**Issue by Ovid-iu** [piwik/piwik-sdk-ios#316]
Hello,

I am trying to implement matomo for a particular scenario, but I am unable to make it work.
I am setting up the matomo tracker with a siteID when the app launches, but after that, I would like to allow the user to change the siteID.
If I make the matomo tracker nil, then redo the setup with the same URL but a different siteID, past this point I do not see the events tracked anymore.
Is this a known issue?

**Comment by brototyp** [comment]
Hi @Ovid-iu and thanks for opening this question.

No, that's not a known issue and there is no immediate reason that comes to my head why that could happen. Can you try to reproduce this in an empty / example project?

**Comment by Ovid-iu** [comment]
Hey @brototyp ,
I will try to do so in an empty project and see the results.

As a side note, I wrote that the fact that I do not see the events tracked anymore - I didn't actually check to see if the events were tracked on the site, but the logs were not showing anymore after changing the siteID.

**Comment by Ovid-iu** [comment]
First of all, I am sorry, there is no issue when changing the site id, I simply forgot to setup the logger again for the new instance, and this was the reason why I was not seeing the logs anymore - again I apologise. 

Secondly, I have found another issue, when setting up the same instance with a new siteId, the timer from the first setup used to dispatch events from the queue remains, so I keep seeing the following message: MatomoTracker [I] No need to dispatch. Dispatch queue is empty.  
If I will setup the instance a third time, there will be 3 separate timers that want to dispatch events from their own queues.

Steps to reproduce:
1. Setup the matomo with the first site id, and call the track method:
matomo = MatomoTracker(siteId: “siteID1”, baseURL: “baseURL”)
matomo.logger = DefaultLogger(minLevel: .verbose)
matomo.track(view: [“LoginScreen”])

2. Setup the same matomo instance with another siteID and call the track method:
matomo = MatomoTracker(siteId: “siteID2”, baseURL: “baseURL”)
matomo.logger = DefaultLogger(minLevel: .verbose)
matomo.track(view: [“LoginScreen”])

3. Setup the matomo instance with the third siteID and call the track method:
matomo = MatomoTracker(siteId: “siteID3”, baseURL: “baseURL”)
matomo.logger = DefaultLogger(minLevel: .verbose)
matomo.track(view: [“LoginScreen”])

By doing so, the logs will show: MatomoTracker [I] No need to dispatch. Dispatch queue is empty multiple times - more than it should. Based on the 30 seconds rule used to dispatch events, I could verify the fact that for each instance, the log was displaying as expected. 

I tried making the instance nil, but this was of no effect. Is there a way to clear the previous timer/queue?

**Comment by brototyp** [comment]
Hey @Ovid-iu, thanks for getting back on that and reporting the other issue. I have the suspicion, there is a retain cycle and the dispatcher is kept.

I'll have a look at it, but it might take a little. Feel free to investigate yourself 😊

**Comment by brototyp** [comment]
Hey @Ovid-iu, I found the issue and implemented a fix. Please have a look at #320.

**Comment by Ovid-iu** [comment]
@brototyp Seems about right, when can this be released into a new version?

**Comment by brototyp** [comment]
This was just released in [version 7.2.0](https://github.com/matomo-org/matomo-sdk-ios/releases/tag/v7.2.0).
