### ISSUE TITLE
Small timeout in URLSession

### ISSUE THREAD

**Issue by MisnikovRoman** [piwik/piwik-sdk-ios#317]
While testing analytics in bad network conditions with 5 sec timeout, i've found that many requests interrupts with timeout error.

Can you make timeout property public?

**Comment by brototyp** [comment]
Hi @MisnikovRoman, thanks for opening this issue.

What do you think about adding a parameter to the `URLSessionDispatcher` initializer which defines the timeout?

**Comment by MisnikovRoman** [comment]
Will be great 👍🏻

**Comment by brototyp** [comment]
> Will be great 👍🏻

Great! I will not be able to do that soon, but I am accepting PRs 😉

**Comment by brototyp** [comment]
Thanks for your work on this. It will be part of the next release.
