### ISSUE TITLE
Update devices info.

### ISSUE THREAD

**Issue by ascherbinin** [piwik/piwik-sdk-ios#318]
Hello.

We noticed that when creating reports, we get strange values for some device models. I would like to update the list of devices.

P.S. Request is ready =)
Best Regards.

**Comment by brototyp** [comment]
Hey @ascherbinin, oh dang. Yes plase. I am more than looking forward to check out your PR.

**Comment by ascherbinin** [comment]
@brototyp 
Well, only one question is whether I can get rights to push the changes. Because now I get an access error when trying to push my branch. Or if you need a different interaction scheme, then tell me how.

Thanks and best regards

**Comment by brototyp** [comment]
Hey @ascherbinin, oh yeah. The pattern here on GitHub is usually to fork the repository, push onto the own fork and then create a PR from the fork. I guess [this help page](https://help.github.com/en/articles/creating-a-pull-request) should help you getting started.

**Comment by ascherbinin** [comment]
Ohh @brototyp big thanks for information. Pull request has already been created, enjoy review.

**Comment by ascherbinin** [comment]
Sorry for close, miss click =(

**Comment by brototyp** [comment]
I just merged the PR. This will be part of the next release. Thanks a lot!
