### ISSUE TITLE
Operating System versions: Unknown since iOS 13

### ISSUE THREAD

**Issue by simonnickel** [piwik/piwik-sdk-ios#322]
Since iOS 13 the Operating System versions statistic shows mostly unknown. During iOS 13 betas it did show iOS 13.1 as value, but since the public release it mostly shows unknown.

Devices are also displayed as unknown, but this should be fixed by https://github.com/matomo-org/matomo-sdk-ios/pull/321

**Comment by notjosh** [comment]
I'm _guessing_ #310 must have broken it, since we're seeing the same - earlier iOS 13 was fine, but then stopped seeing them around the same time we bumped the pod. I'll do some investigating!

**Comment by notjosh** [comment]
Update: yyyep, seems #310 broke the user agent reporting (maybe only on iOS 13?). There's a PR #323 that should fix it if you need it in a hurry.

**Comment by brototyp** [comment]
This bug was fixed by @notjosh and will be part of the next release.

@simonnickel thanks a lot for reporting and @notjosh thanks a lot for debugging and fixing!

**Comment by simonnickel** [comment]
@notjosh thanks, working fine again :)

**Comment by brototyp** [comment]
This was just released in [version 7.2.0](https://github.com/matomo-org/matomo-sdk-ios/releases/tag/v7.2.0).
