### ISSUE TITLE
Device information not supplied

### ISSUE THREAD

**Issue by omanikhi** [piwik/piwik-sdk-ios#324]
I can't find anything in the visit log or the visitor profile about what Apple device they used and its model. I can see the screen resolution though. Shouldn't these kind of information be automatically collected and sent to the server by the SDK? Or do I have to do this manually in some way?

![image](https://user-images.githubusercontent.com/1851344/67922573-642a8b80-fbab-11e9-9c4b-26b5a4d353ea.png)

**Comment by brototyp** [comment]
Hi @omidontop, thanks for reporting. This bug got introduced in 7.0.0 and is already fixed but not released yet. For more information please check [this issue](https://github.com/matomo-org/matomo-sdk-ios/issues/322).

**Comment by omanikhi** [comment]
Hi @brototyp, thank you for your response! Awesome, then I'll wait for the next release. 👍
