### ISSUE TITLE
New session not starting

### ISSUE THREAD

**Issue by grigory9** [piwik/piwik-sdk-ios#325]
When I try to manually start a new session using ```MatomoTracker::startNewSession()``` then it is not started at all and all new events belongs to previous session. 

I think the problem is inside ```MatomoTracker::startNewSession()``` method. There new session is created, but all new events doesn't know that new session started. The probable resolution could be setting ```nextEventStartsANewSession``` flag with ```true``` value

**Comment by grigory9** [comment]
Made PR https://github.com/matomo-org/matomo-sdk-ios/pull/326

**Comment by brototyp** [comment]
This was just released as part of 7.2.2
