### ISSUE TITLE
Multiple user on same device, Profile getting merge.

### ISSUE THREAD

**Issue by vishnukhaitan** [piwik/piwik-sdk-ios#336]
If we are login with two different users on same iOS device. events are merging for both users.
If we go in View visiter profile i can see events are merged with older user.

**Comment by brototyp** [comment]
Hi @vishnukhaitan, thanks for getting in touch. Can you maybe get a little more in detail what you are doing, what you would expect and what happens?

**Comment by vishnukhaitan** [comment]
@brototyp 
Find below steps :-
1)Login with uses A-> set user id A1 -> log event 1
2)Logout 
3)Login with user B -> set user id B1 -> log event 2
4)Matomo admin panel we can see same visiter id for two different users and events triggered by user B are merged in user A.

What should we do in iOS app to handled this case.

**Comment by brototyp** [comment]
Hi @vishnukhaitan, thanks for the additional information. If I am correct, a user is deemed the same (on the backend) if the `forcedVisitorId` is the same. The `userId` is merely a human readable identifier for this user.
One way to actually have different users on the backend would be to set different `forcedVisitorId`s for these two users. In backend terms this would be called a `cid`. I guess in your case it would make sense to either derive the value off of your `userId` or get the value from the server whenever the user logs in, so it will always be the same. 

A few thoughts though:

* I don't know if it is a good idea if one user has the same `forcedVisitorId` on multiple devices. Probably not.
* If you set the `forcedVisitorId` to a new value, you'll still keep the session based information. This means that this user is seen as a recurring user on the backend. Right now the SDK doesn't provide a way to change this.

@mattab Do you have any thoughts about this?

**Comment by brototyp** [comment]
I will close this for now. Please still feel free to respond and we can reopen.
