### ISSUE TITLE
Getting error when dispatching events

### ISSUE THREAD

**Issue by andreaslif** [piwik/piwik-sdk-ios#337]
MatomoTracker [I] Start dispatching events
_Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
Could not signal service com.apple.WebKit.Networking: 113: Could not find specified service_
MatomoTracker [I] Dispatched batch of 2 events.
MatomoTracker [I] Finished dispatching events

I think it's trying to access the webView object (WKWebView), which is no longer there. It's being set to nil in generateDefaultUserAgent(_ completion: @escaping (String) -> Void) in URLSessionDispatcher. Commenting out webView = nil removes the error for me.

**Comment by brototyp** [comment]
Hi @andreaslif, thanks for your report. Can you try out the version on this branch `bugfix/329-missing-device-info` to see if it fixes you issue?

**Comment by andreaslif** [comment]
> Hi @andreaslif, thanks for your report. Can you try out the version on this branch `bugfix/329-missing-device-info` to see if it fixes you issue?

No problem! Sure I can give that a try, but I'm not really sure how to do it. I installed the SDK via CocoaPods. Can I use CocoaPods to specify a branch? Or do I have to do it some other way? (I'm not very experienced with either github or CocoaPods)

**Comment by brototyp** [comment]
Hey @andreaslif,

yeah, you can define a branch in your Podfile. It should look like this then:

`pod 'MatomoTracker', :git => 'https://github.com/matomo-org/matomo-sdk-ios.git', :branch => 'bugfix/329-missing-device-info'`

After that just perform a `pod install`.

**Comment by andreaslif** [comment]
Sorry for the late response and thanks for the info. It looks like you’ve merged the branch now? I got an error message when I tried to run pod install

**Comment by brototyp** [comment]
Hi @andreaslif, yeah the according PR was merged and released as part of release `7.2.1`. Can you have a look if your issue is fixed in the latest release?

**Comment by andreaslif** [comment]
Sorry for the late reply. It’s not fixed in 7.2.1, I’m getting the same error.

**Comment by brototyp** [comment]
Hey @andreaslif, is there anything new in this regard? Do you actually see an issue that you are missing events on the server?

[It looks like the message itself shouldn't be a big issue](https://developer.apple.com/forums/thread/112095).

**Comment by brototyp** [comment]
The latest release, version 7.3, contains a major update un user agent generation that should fix this issue. 
I will close this ticket for now. Please feel free to comment here, if it doesn't.
