### ISSUE TITLE
Integrate extended parameters with "token_auth" support

### ISSUE THREAD

**Issue by Moony83** [piwik/piwik-sdk-ios#338]
Thank you so much for this pod. It works beautifully!

However, i ran into a rather niche problem: My App talks to its backend through a VPN tunnel with NAT. Naturally, the on-prem Matomo instance can only see the NATed client IP.

I'm trying to override the IP. The [Matomo API documentation](https://developer.matomo.org/api-reference/tracking-api) points to using the parameter **&cip=<IPADDRESS>** in conjunction with a token passed with **&token_auth=<TOKEN>**

I'd live to be able to pass these as optional values to the Matomo Pod. Any chance on treating this as an enhancement?

**Comment by brototyp** [comment]
Hi @Moony83,

thanks for your question. Yeah, I think it's quite a niche problem.
I don't think the SDK should support parameters that need the `token_auth` parameter. I don't want to encourage users adding this parameter. Imho this might be a quite a security question there as well. It might be tricky to actually hide the parameter.

But, if you still want to do something like that, I think there is a workaround for your case. We do support [sending custom events](https://github.com/matomo-org/matomo-sdk-ios#sending-custom-events) in the SDK as well. Unfortunately you loose the convenience "track view" functions as such, but you could write them as extensions yourself. I am thinking about something like this (untested):

```swift
extension MatomoTracker {
    public func track(ip: String, token: String, view: [String], url: URL? = nil, dimensions: [CustomDimension] = []) {
        let event = Event(tracker: self, action: view, url: url, dimensions: dimensions, customTrackingParameters: ["cip": ip, "token_auth": token])
        track(event)
    }
}
```

So, depending on your use case, that should get the job done. What do you think?

**Comment by brototyp** [comment]
I will close this for now. Please still feel free to respond and we can reopen.
