### ISSUE TITLE
Devices needs to be updated

### ISSUE THREAD

**Issue by swifty-tim** [piwik/piwik-sdk-ios#340]
`case "iPhone12,8":  return "iPhone SE 2nd Gen"`

```
case "Watch5,1":      return "Apple Watch 40mm (Series 5, GPS)"
case "Watch5,2":      return "Apple Watch 44mm (Series 5, GPS)"
case "Watch5,3":      return "Apple Watch 40mm (Series 5, GPS + Cellular)"
case "Watch5,4":      return "Apple Watch 44mm (Series 5, GPS + Cellular)"
```

**Comment by swifty-tim** [comment]
Found this link for confirming the names -> https://gist.github.com/adamawolf/3048717#file-apple_mobile_device_types-txt-L98

**Comment by brototyp** [comment]
Hey @swifty-tim, I am open for a PR in this regard 😊

**Comment by brototyp** [comment]
Hi @swifty-tim, I decided to completely remove the property. In the latest version of the SDK we don't use it anymore (the matching is done on backend side using the platform name).
