### ISSUE TITLE
Custom variable in the scope of the screen iOS

### ISSUE THREAD

**Issue by filipe56** [piwik/piwik-sdk-ios#341]
I added custom variable in the scope of the screen on android 

Example in android:

TrackHelper.track(mVisitVars.toVisitVariables()).screen(screenPath).title(title)
                .variable(1, "variable 1", getCustomVariableA())
                .variable(2, "variable 2", getCustomVariableB())
                .with(tracker);

but on iOS I'm having a problem with this implementation. How to add custom variable in the scope of the screen on iOS?

**Comment by brototyp** [comment]
The iOS SDK doesn't support custom variable tracking, but [custom dimension tracking](https://matomo.org/faq/general/faq_21117/). Right now the "visit scope" is [directly supported by the SDK](https://github.com/matomo-org/matomo-sdk-ios#custom-dimension). If you need to send custom dimensions only for the page scope, you should be able to leverage the `customTrackingParameters`. Have a look [here](https://github.com/matomo-org/matomo-sdk-ios#sending-custom-events) for more details.
