### ISSUE TITLE
iOS does not dispatch events after 30 seconds if the OS kills the app

### ISSUE THREAD

**Issue by chreck** [piwik/piwik-sdk-ios#344]
**Description**
Since iOS 13 the handling of the application, if it is using a lot of memory and in background, it kills the app. So it can happen if a background task is running and it is finished later. It will not send the last events to the matomo server because after 30 seconds the app get killed. The cause is that the MatomoTracker class, the dispatcher is waiting for 30 seconds until it is sending the events out.

**Solution**
A solution would be to decrease the time interval from 30 seconds to about 15 seconds.

**Sources**
- https://stackoverflow.com/questions/60704085/ios-app-get-killed-in-background-if-spend-more-than-30-seconds-ios-13-mostly
- https://github.com/matomo-org/matomo-sdk-ios/blob/f99ad2a4eaf80910b39bbd65550c40460df7ba23/MatomoTracker/MatomoTracker.swift#L200

**Comment by brototyp** [comment]
Open discussion on the PR

**Comment by brototyp** [comment]
I'll close this for now. @chreck fixed this by changing the `dispatchInterval` to 15 in their own app.
