### ISSUE TITLE
Operating Systems report: Small percentage of requests shows up as "Mac" or "unknown"

### ISSUE THREAD

**Issue by gereons** [piwik/piwik-sdk-ios#351]
Using Matomo 7.2.x in my iOS app, I see a small number of requests (about 0.2% of total requests) show up as "Mac" or "unknown/unbekannt" in my operating systems report. Given this low number I have thus far been unable to reproduce this problem in out test environment, all requests made there are correctly identified as e.g. "iOS 13.7".

Looking at the custom dimensions of the visits from "mac/unknown", I know for certain that those are in fact iOS app instances. Some of those apps were built with v7.2.0, some use 7.2.1, but nothing older.

Stepping through the initialization code I can see that `URLSessionDispatcher.generateDefaultUserAgent()` is called and does in fact produce a valid-looking UA string like `Mozilla/5.0 (x86_64; CPU iPhone OS 13_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 MatomoTracker SDK URLSessionDispatcher`.

I never pass any custom user agent string to the `MatomoTracker` initialization.

What can I do to further debug this and hopefully get those requests to be counted as the correct iOS version?

TIA.

**Comment by Findus23** [comment]
Hi,

This could be related to https://github.com/matomo-org/matomo-sdk-ios/issues/347#issuecomment-695298279

**Comment by Findus23** [comment]
You could take a look at the access log of your server to check if you could find the exact user agents of the users that got detected incorrectly?

**Comment by gereons** [comment]
I've found four requests in yesterday's logs that are responsible for two "Mac" and two "unknown" reports - times and IP address prefixes match.

These two were counted as "Mac":

```
10.0.0.8 - - [21/Sep/2020:13:27:26 +0000] "POST /matomo.php HTTP/1.1" 200 55 "-" "MyApp/114 CFNetwork/1197 Darwin/20.0.0" "x.y.z.0"
10.0.0.8 - - [21/Sep/2020:09:09:54 +0000] "POST /matomo.php HTTP/1.1" 200 55 "-" "MyApp/114 CFNetwork/1197 Darwin/20.0.0" "x.y.z.0"
```
i.e. this looks like the default User-Agent for URLSession. 114 is in fact the build number for the current release of the app, "Darwin/20" is iOS 14 afaict, and that version was built on September 2nd using SDK 7.2.1

These next two were counted as "unknown":

```
10.0.0.8 - - [21/Sep/2020:21:03:34 +0000] "POST /matomo.php HTTP/1.1" 200 55 "-" "MatomoTracker SDK URLSessionDispatcher" "x.y.z.0"
10.0.0.8 - - [21/Sep/2020:13:32:30 +0000] "POST /matomo.php HTTP/1.1" 499 0 "-" "MatomoTracker SDK URLSessionDispatcher" "x.y.z.0"
```
i.e. somehow the UA extraction from WKWebView has failed, if I understand the code correctly.

**Comment by brototyp** [comment]
Thanks both of you for the feedback. 

I think we need to rethink our UserAgent generation. Right now the SDK asks the WebView to generate the UserAgent and will then replace `iPhone` with the actual iPhone version. There are just to many issues with it:

* WebKit as a dependency
* Asynchronous code: There is no synchronous way to let a WKWebView generate the UserAgent
* When the format of the UserAgent returned by WkWebView changes our code might break (I guess that's what is happening here)

I opened a [PR](https://github.com/matomo-org/matomo-sdk-ios/pull/353) that completely changes, how we generate the UserAgent. @gereons can you please have a look at it, to see if it works in your case?

**Comment by gereons** [comment]
With one minor exception, this looks good to me, thanks! See https://github.com/matomo-org/matomo-sdk-ios/pull/353#issuecomment-703461977

**Comment by brototyp** [comment]
The latest release, version 7.3, contains a major update un user agent generation that should fix this issue. 
I will close this ticket for now. Please feel free to comment here, if it doesn't.
