### ISSUE TITLE
Apple Watch support

### ISSUE THREAD

**Issue by philippmayrth** [piwik/piwik-sdk-ios#352]
Are there any plans to support this SDK on the Apple Watch?

**Comment by brototyp** [comment]
Hey @philippmayrth, thanks for asking.

There is no plan yet. There is one big question we need to define: Do we want to let the watch send the events themselves or should we send the data via an accompanying iPhone app? With the watches small battery it is even more important to save it and to reduce the network traffic even more so sending it via the iPhone could save quite a bit. On the other hand: There are watchOS only Apps now without an iPhone App. A bit of a tricky situation 😊 

If you want to track events happening on the iPhone and if you already established some form of communication between your watch app and the iPhone app you could use that to then send the events from the iPhone side without any changes in the SDK.

**Comment by philippmayrth** [comment]
Thanks for your quick response.

Hadn’t thought about the battery, I’m currently developing a watch only app so I’m just going to leave the tracking out of there.

**Comment by brototyp** [comment]
Alright. Good luck!
