### ISSUE TITLE
Can I use customTrackingParameters to override the default cdt time format?

### ISSUE THREAD

**Issue by Isaacwhyuenac** [piwik/piwik-sdk-ios#360]
Hi, I would like to ask if I can pass a `cdt` in `customTrackingParameters` to override the default `cdt` value (ISO8601) value of the tracker? I would want to override it because I want it to be in unix timestamp (13 digits).

**Comment by brototyp** [comment]
Hi @Isaacwhyuenac, I think that should work.

Out of curiosity: Why do you want to use a unix timestamp instead of the current ISO8601 format?

**Comment by Isaacwhyuenac** [comment]
@brototyp thanks for the reply. But it looks like it is not working because there would have two cdt key in the final url string. One in iso8601 and one in unix time stamp. 

Want this feature because we have some tracking events that fire together in some mini seconds difference. It would help to visualise and order the user’s journey more fully.

**Comment by brototyp** [comment]
Oh, your are correct. Currently, there is no way to replace the value of a parameter. You can only add some.

I think your use case actually is one that the SDK should handle per default. I'll implement a fix for it.

**Comment by brototyp** [comment]
Fixed and merged. This will be in the next release.

**Comment by Isaacwhyuenac** [comment]
Thank you for the reply, but your changes are somehow not what I am expecting, which is to make cdt value unix timestamp (something like 1607875978284).

**Comment by brototyp** [comment]
> Thank you for the reply, but your changes are somehow not what I am expecting, which is to make cdt value unix timestamp (something like 1607875978284).

That's true. The cdt parameter is still a ISO8601 timestamp, but now it does contain milliseconds. Is that sufficient, or is there a reason to have the unix timestamp specifically?

**Comment by Isaacwhyuenac** [comment]
Because our data pipeline use unix timestamp specifically 🤣, but also the [matomo documentation](https://developer.matomo.org/api-reference/tracking-api) somewhat allows us to use unix timestamp too. Just wondering if [here](https://github.com/matomo-org/matomo-sdk-ios/blob/76bdcb352a16d745d929f07b5319ff9808f8ad14/MatomoTracker/EventAPISerializer.swift#L4) can somehow allow user to override the default params format on every request, using something like JavaScript Array.reduce function. I am not a Swift developer, so I don't know if Swift can do this or is [here](https://github.com/matomo-org/matomo-sdk-ios/blob/76bdcb352a16d745d929f07b5319ff9808f8ad14/MatomoTracker/EventAPISerializer.swift#L4) the correct place to allow my desired behavior. Hope I have made my case clear. 

Some matomo implementation, like in obj-c and js use unix timestamp. Java, for example, use iso8601 but allows overriding. So somewhat I am hoping an alignment of matomo sdk.

**Comment by brototyp** [comment]
Hi @Isaacwhyuenac, I see. I think it would be a good idea to be able to override some parameters with exactly the ones you like to use. There is the risk in accidentally overriding some, but I think that can be mitigated a bit by documentation.

**Comment by brototyp** [comment]
Hey @Isaacwhyuenac, can you try out this PR: #370. That should work fine now.

**Comment by Isaacwhyuenac** [comment]
@brototyp It seems working fine. Thanks

**Comment by brototyp** [comment]
This is now implemented and part of the latest release, v7.5
