### ISSUE TITLE
Follow up from new custom action parameters

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik-sdk-ios#363]
Follow up from https://github.com/matomo-org/matomo-sdk-ios/pull/355 and https://github.com/matomo-org/matomo-sdk-ios/issues/354

We just realised that this new `ca=1` parameter should not be sent in goals and ecommerce tracking requests but only for events and optionally content tracking requests (if this is implemented). 

If I understand the PR right this is already the case but wanted to double check to make sure `&ca=1` is not sent for any goal tracking or ecommerce tracking request.

Cheers

**Comment by brototyp** [comment]
Hey @tsteur,

thanks for bringing this one in. I wanted to check back, to make sure we get it correct this time.

I am not sure if I clearly understand when the parameter should be sent and when it shouldn't. I am esp. curious about events we haven't implemented yet, e.g. media analytics and such.

As the [documentation](https://developer.matomo.org/api-reference/tracking-api) isn't really explicit about this: Is there a definition on when these events should be sent and when not? In this implementation everything is an event. A page view, an e-commerce tracking event, an action ...

Thanks a lot!

**Comment by tsteur** [comment]
Hi @brototyp in this case you basically only need to append it for an event tracking request. Not for any other kind of tracking requests.

**Comment by brototyp** [comment]
Thanks @tsteur 
This is released in v7.4
