### ISSUE TITLE
Deprecation message "use trackEventWithCategory instead" refers to non-existent function

### ISSUE THREAD

**Issue by cjhines** [piwik/piwik-sdk-ios#367]
https://github.com/matomo-org/matomo-sdk-ios/blob/e17bb9046e8970dbc151309c145c4de2f1b1339e/MatomoTracker/MatomoTracker.swift#L451

`trackEventWithCategory` does not exist.

Is this a typo, or is it referring to an upcoming function?

**Comment by brototyp** [comment]
Hi @cjhines, thanks for checking. This is a typo. It should say "use track(eventWithCategory:action:name:number:url instead". It's not corrected in 379e288a909e51a75421eb0a5be81485562808c3 and should be fixed in the next release.
