### ISSUE TITLE
Swift Package Manager does not find 7.4, only goes up to 7.2.2

### ISSUE THREAD

**Issue by simonnickel** [piwik/piwik-sdk-ios#371]
Not sure if I am doing something wrong or SPM is stupid ...

But it seems like its ignoring 2-digit version numbers. I can specify all 3-digit versions like the 7.2.2, but not latest released version 7.4. Even when defining 7.0.0 > Next Major, it always resolves only up to 7.2.2.

Could you please re-tag the latest version?

**Comment by roelvanderkraan** [comment]
I have the same issue

**Comment by brototyp** [comment]
Oh. I wasn't aware about that. Thanks for letting me know. I just released Version 7.4.1. Same content, just a new tag and a new version on CocoaPods.
