### ISSUE TITLE
The minimum version of Piwik on the site for the work of iOS SDK

### ISSUE THREAD

**Issue by dmytriigolovanov** [piwik/piwik-sdk-ios#376]
We have the site with `Piwik 3.3.0` and want to add tracking to the application associated with this site.

Are we able to use the SDK for our application or do we need to update Piwik on the site?

**Comment by brototyp** [comment]
Hey @dmytriigolovanov, I am not sure if any of the major APIs changed since version 3.3.0. There might be some features not supported by either the website or the client SDK. Unfortunately I am not able to give an exact answer.
