### ISSUE TITLE
eCommerce: tracking product views /  cart updates

### ISSUE THREAD

**Issue by GerdC** [piwik/piwik-sdk-ios#378]
How can I track product view and / or update cart?

Method trackOrder(...) does something similar but not the same.

The cases are described here: https://matomo.org/docs/ecommerce-analytics/#tracking-product-views-in-matomo-optional

and here https://matomo.org/docs/ecommerce-analytics/#tracking-cart-updates-in-matomo-optional

**Comment by brototyp** [comment]
Hi @GerdC, right now there is only the order tracking events implemented in the iOS SDK. Tracking views or cart updates _should_ be possible with custom `Event`s but I can't give more detail on that.
