### ISSUE TITLE
About the usage of customTrackingParameters

### ISSUE THREAD

**Issue by gyosida** [piwik/piwik-sdk-ios#387]
Hello, please I'd like your help with the customTrackingParameters feature.

I have the following use case: 
I want to track a soccer team selection event, but is relevant for the business to know about the team id, name, team's tournament and if it was a enabled or disabled (bool) event.

I don't find the description on your Readme 100% clear so I'd like to confirm:

- Can I send a map with these custom parameters? team_id, team_name, enabled, tournament_id
- Am I only able to send an already predefined set of parameters? if so, why?
- Do you recommend to use a custom dimension instead? Personally, I think this options is a little bit "advance" for this kind of storing related to event info stuff.

Thanks in advance!

**Comment by brototyp** [comment]
Hey @gyosida, 

your question is quite dependent on how you want to analyze your information on the backend as well. 

There are [events](https://matomo.org/docs/event-tracking/) (unlike page views) in Matomo that would probably fit your need the best. Events by themselves have 4 parameters: Categories, Actions, Names and Values. If you can fit your information in there somewhere, that would be the best solution I guess.

Custom dimensions are an option, but they are best suited for generic information such as if you want the soccer team be a dimension of all (or many) of the events you are tracking. There is a performance impact on the backend side when using dimensions and there is a [default limit of 5 dimension all together which can be changed](https://matomo.org/docs/custom-dimensions/).

**Comment by brototyp** [comment]
I'll close this for now. Please let me know if this is still an issue.
