### ISSUE TITLE
Legacy Build System errors out in Xcode 13 Beta

### ISSUE THREAD

**Issue by sieren** [piwik/piwik-sdk-ios#390]
Building the SDK with Carthage and Xcode 13 Beta currently causes the build to fail due to:
```Prepare build
error: The Legacy Build System will be removed in a future release. You can configure the selected build system and this deprecation message in File > Workspace Settings.
Build Preparation
The Legacy Build System will be removed in a future release. You can configure the selected build system and this deprecation message in File > Workspace Settings.
```

I suppose this was a warning in earlier versions and has now been upgraded to an error by Apple.

I'm happy to do a PR and bump this up to the new build system.

**Comment by billburgess** [comment]
+1

**Comment by sieren** [comment]
@brototyp quick question, when do you expect to do a new release? it currently breaks building both locally and CI with xcode13.

**Comment by brototyp** [comment]
Hey @sieren, I wanted to double check #397 and merge and release that as well. I think I should be able to do that today.
