### ISSUE TITLE
Swift Package Manager

### ISSUE THREAD

**Issue by setri45** [piwik/piwik-sdk-ios#398]
Hi, 

Is it possible to add Swift Package Manager support ? 
It would be good. 

Thanks

**Comment by simonnickel** [comment]
Hey @setri45,
I am using the package over SPM, just add it like you would any other package.

I guess the readme should be updated though.

**Comment by brototyp** [comment]
Thanks for your question @setri45 and thanks for the answer @simonnickel 😊

I just updated the readme to reflect SPM support
