### ISSUE TITLE
url in events should default to the last url viewed

### ISSUE THREAD

**Issue by larsriehn** [piwik/piwik-sdk-ios#400]
At the moment `url` is set here at the creation of `Event`:
`self.url = url ?? tracker.contentBase?.appendingPathComponent(action.joined(separator: "/"))`

The idea is to have an identical behaviour to the matomo-sdk-android, where url is the last screen view, see
https://github.com/matomo-org/matomo-sdk-android/issues/92
for more information.

**Comment by brototyp** [comment]
Hey @larsriehn, funny that the Android ticket refers to an older implementation of the iOS ticket. 

Just to understand the issue better. Is this basically the proposal?

```swift
if action.empty && let lastUrl = lastUrl {
    self.url = lastUrl
} else {
    self.url = url ?? tracker.contentBase?.appendingPathComponent(action.joined(separator: "/"))
    lastUrl = self.url
}
```

**Comment by brototyp** [comment]
I am closing this ticket for now. Please get in touch if this issue still exists.
