### ISSUE TITLE
SwiftPM integration issue (Release v7.5)

### ISSUE THREAD

**Issue by Foboz** [piwik/piwik-sdk-ios#402]
Hey team, same issue as #371

Since SwiftPM doesn't support tag form `MAJOR.MINOR` without `PATCH` component, can you please use 3-components tags?

Some background and fixed on SwiftPM side, but it will be available with Swift 5.6:
https://github.com/apple/swift-package-manager/blob/main/CHANGELOG.md#swift-56
https://github.com/apple/swift-package-manager/pull/3649

**Comment by VincentDurandChewbi** [comment]
> Hey team, same issue as #371
> 
> Since SwiftPM doesn't support tag form `MAJOR.MINOR` without `PATCH` component, can you please use 3-components tags?
> 
> Some background and fixed on SwiftPM side, but it will be available with Swift 5.6: https://github.com/apple/swift-package-manager/blob/main/CHANGELOG.md#swift-56 [apple/swift-package-manager#3649](https://github.com/apple/swift-package-manager/pull/3649)

Same issue, i was forced to use the commis hash to get the specific version i needed

**Comment by brototyp** [comment]
Hey @Foboz and @VincentDurandChewbi, thanks for bringing this up to my attention. That's totally on me. I forgot this issue and released the last one without a patch version. I'll take care releasing a new version

**Comment by brototyp** [comment]
I just pushed Version 7.5.1

**Comment by VincentDurandChewbi** [comment]
Thank's a lot, works well :)
