### ISSUE TITLE
ID configuration (iOS app)

### ISSUE THREAD

**Issue by danielagiraldofletx** [piwik/piwik-sdk-ios#405]
Hello, i need a assistant... on the id configuration in a mobile app tracking! the names doesnt appear! Actually I'm using SDK so I don't know what could be happening. I hope you can help me.

**Comment by brototyp** [comment]
Hi @danielagiraldofletx, 

thanks for your report. Unfortunately I am not sure what your problem is. Do you mind rephrasing it? Do you have an example project? What are you trying to achieve? What is the issue you are encountering?

**Comment by brototyp** [comment]
Closing this for now. Feel free to open it again if needed.
