### ISSUE TITLE
iOS SDK does not track view.

### ISSUE THREAD

**Issue by jinjin-lee** [piwik/piwik-sdk-ios#410]
Hello
I am a ios developer and would like to integrate matomo sdk in my project.
But sdk tracked view just once at first and is not working any more.
I am trying to find solution but i cannot find issue.
Could you help me for this issue?

Thanks

**Comment by devzhr** [comment]
try to extend UIViewController
```swift
extension UIViewController {
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        matomoTracker.track(view: [self.title])
    }
}
```

**Comment by brototyp** [comment]
Hey, thanks for the report. How did you initialize the `matomoTracker`?
