### ISSUE TITLE
Reset Session and IDs

### ISSUE THREAD

**Issue by t-unit** [piwik/piwik-sdk-ios#417]
Currently there seems to be no way to reset session information (`sessionsCount`, `firstVisit`, ...) as well as the visitor id. I would propose some functionality that enables deleting all stored data in the user defaults for a given `MatomoTracker` instance that keeps the instance usable and in correct state afterwards. 

One use case for this is binding the session information to a user and not to the device. E.g. calling reset after user-logout and not keeping the session count etc.

Happy to supply PR with the proposed feature.

**Comment by SW-Vincent** [comment]
Hi, just a question about this topic : what is the default behaviour of a session then ?

**Comment by brototyp** [comment]
This was implemented in #434 and will be in the next release
