### ISSUE TITLE
Device information and operating system not being tracked

### ISSUE THREAD

**Issue by TrabelsiAchraf** [piwik/piwik-sdk-ios#420]
I migrated to 7.5.2 and now I have issue that all device information and the operating system are not tracked anymore.

**Comment by brototyp** [comment]
Hi @TrabelsiAchraf, from which version did you upgrade? Did you already see [this](https://github.com/matomo-org/matomo-sdk-ios/wiki/FAQ#in-the-backend-devies-are-just-shown-as-apple-iphone-how-do-i-get-more-information-such-as-specific-device-or-os-version) FAQ entry regarding OS and device info tracking?

**Comment by TrabelsiAchraf** [comment]
> Hi @TrabelsiAchraf, from which version did you upgrade? Did you already see [this](https://github.com/matomo-org/matomo-sdk-ios/wiki/FAQ#in-the-backend-devies-are-just-shown-as-apple-iphone-how-do-i-get-more-information-such-as-specific-device-or-os-version) FAQ entry regarding OS and device info tracking?

Hi @brototyp, I'm so sorry, it's me. Actually we have an API to control the option OptOut to enable/disable the tracking, and we have an issue with this IPA last time. I will close the issue. I apologize for the inconvenience.

**Comment by brototyp** [comment]
Hey @TrabelsiAchraf, no worries. Thanks a lot for the followup! Happy new Year!
