### ISSUE TITLE
Cannot create an NSPersistentStoreCoordinator with a nil model

### ISSUE THREAD

**Issue by ondrejmirtes** [piwik/piwik-sdk-ios#44]
When integrating this library into my app via Cocoapods, additional steps are needed in order for it to work, otherwise this message pops up and the app crashes.

I had to manually create piwiktracker.momd file with `momc` utility from Xcode, and include it in my app bundle. Is it possible to automate this process in further versions?

**Comment by docterd** [comment]
Has this issue been fixed with the latest Podfile? Getting the same problem here.
