### ISSUE TITLE
PIWIK PRO SDK Breaks Code

### ISSUE THREAD

**Issue by yourajpawar** [piwik/piwik-sdk-ios#441]
Hello,
I installed PIWIK PRO SDK via **pod 'PiwikPROSDK' '~> 1.2.1'** then when i build code i get random errors in my native code XYZ header file not found and erros if fixed keep increasing. When i uninstall PIWIKI PRO SDK pod then build succeeds fine. Not sure what is PIWIK PRO interferring. If I install **pod 'MatomoTracker', '~> 7.5'** this works fine builds the code fine.
Need help for PIWIK PRO SDK.
I followed this document https://developers.piwik.pro/en/latest/data_collection/mobile/Piwik_PRO_SDK_for_iOS.html#sdk-configuration

**Comment by brototyp** [comment]
Hi @yourajpawar, thanks for getting in touch. The PiwikPROSDK is not affiliated with the Matomo SDK here. Please get in touch with them [here](https://github.com/PiwikPRO/piwik-pro-sdk-framework-ios).

[Here is a page](https://matomo.org/piwik-pro-vs-matomo/) that explains the difference between PiwikPro and Matomo.
