### ISSUE TITLE
Invalid instructions on SPM integration

### ISSUE THREAD

**Issue by epicchris** [piwik/piwik-sdk-ios#444]
## Issue
Current instructions recommend using:
```
.package(url: "https://github.com/matomo-org/matomo-sdk-ios.git", from: "v7.5"),
```
when integrating through SPM, but this will result with:
```
Invalid semantic version string 'v7.5'
```
error while doing so.

## Fix

Proper integration through SPM requires:
```
.package(url: "https://github.com/matomo-org/matomo-sdk-ios.git", from: "7.5.0"),
```
README.md should also note that product within `matomo-sdk-ios` is called `MatomoTracker`, so one can integrate SPM dependency as:
```
dependencies: [
                .product(name: "MatomoTracker", package: "matomo-sdk-ios"),
```

**Comment by brototyp** [comment]
Thanks a lot for the report. I fixed this in #459
