### ISSUE TITLE
Privacy.xcprivacy UserDefault for offline events management  

### ISSUE THREAD

**Issue by nathsociete** [piwik/piwik-sdk-ios#446]
Hello,

Following the [issue 137](https://github.com/matomo-org/matomo-sdk-ios/issues/137), I have included the [UserDefaultsQueue](https://github.com/matomo-org/matomo-sdk-ios/blob/32c2353d5b57f9e144f199a544c7fe1df9561236/Example/ios/iOS%20Example/UserDefaultsQueue.swift#L4) class you gave for offline events management in your example inside the code of my app.

As this class refere to [UserDefaults](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278401) can you precise what kind of reason for the privacy data i have to give ? 
CA92.1 or C56D. 1 ?

Thank you in advanced.

**Comment by brototyp** [comment]
Hi @nathsociete, I just released version 7.6.0 which contains this PR: #448

In there, it's defined as CA92.1.

Please let us know about your experience.
