### ISSUE TITLE
SDKs that require a privacy manifest and signature

### ISSUE THREAD

**Issue by enual** [piwik/piwik-sdk-ios#447]
Customer reached out that they use  the Matomo SDK in their apps.

Since there is a requirement from Apple that all SDKs from
third-party providers by May 2024 a data protection manifest file (Privacy
Manifest), they  want to make sure that
Matomo SDK meets Apple's requirements by deadline.

They are asking if we can confirm that by the month of May,
Privacy Manifest will be available for the Matomo SDK.

They want to make sure that their application has the latest compliant with data protection and regulations, and runs smoothly on the App Store.

Information about this can be seen on Apple website: [Upcoming third-party SDK requirements](https://developer.apple.com/support/third-party-SDK-requirements/#:~:text=SDKs%20that%20require%20a%20privacy%20manifest%20and%20signature&text=Starting%20in%20spring%202024%2C%20you,as%20part%20of%20the%20update.)

**Comment by felipe-nipper** [comment]
Matomo should only be required to comply with [Required reason APIs](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api]). 

I created a PR(#448) that should fix this.

**Comment by atom-box** [comment]
Here is the alternate link for @felipe-nipper  URL ^^
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api/

**Comment by atom-box** [comment]
We had another person request this today.

> We have a request from an internal team regarding the below where a privacy manifest is required to be able to continue using Matomo för iOS from 1st of May.

**Comment by brototyp** [comment]
Thanks @felipe-nipper! I just merged the PR.

This is part of Version 7.6.0

**Comment by qasimmajeed** [comment]
@brototyp  i just used 7.6.0 via pod but its not showing the manifest file after update.

Screenshot.
![Uploading Screenshot 2024-05-19 at 10.43.53 PM.png…]()
