### ISSUE TITLE
Swift bridge

### ISSUE THREAD

**Issue by mattiaslevin** [piwik/piwik-sdk-ios#49]
Temporary solution for Swift developers.

**Comment by abellee** [comment]
so how to write in the bridge file

**Comment by brototyp** [comment]
Hi @abellee, thanks for your message. We are currently rewriting the whole SDK in Swift. We would love if you want to join and help: https://github.com/piwik/piwik-sdk-ios/issues?q=is%3Aopen+is%3Aissue+label%3Aswift3

**Comment by brototyp** [comment]
Hi, thank you for your Pull Request. We dropped ongoing development for version 3 of this SDK. Please consider looking into version 4, which is completely rewritten in Swift.
