### ISSUE TITLE
Migrate to Swift

### ISSUE THREAD

**Issue by mattiaslevin** [piwik/piwik-sdk-ios#50]
Rewrite the SDK in Swift.

**Comment by Erulezz** [comment]
+1 

Would really like to see this.

**Comment by pjc-is** [comment]
+1

that would be awesome!

**Comment by mattiaslevin** [comment]
Ok, I will start on a Swift implementation.
If anyone care to help out please let me know.

**Comment by Erulezz** [comment]
If you need help with features or testing let me know!

**Comment by funky-monkey** [comment]
+10

**Comment by mattiaslevin** [comment]
ok ok, I have started and have something, lets see if I can get it to a shareable state.

**Comment by Urkman** [comment]
What is the status here? How can I use Piwik in my Swift Project?

**Comment by Erulezz** [comment]
You can use this Objective-C project in a Swift project with a bridging header. More info;

https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html

**Comment by perlguy99** [comment]
I'd love to see this too.  How far along are you?  Need any help?  I may be able to help with it, if needed.

**Comment by mattab** [comment]
Hi @perlguy99 @Erulezz @Urkman @funky-monkey - your help would be very welcome! @mattiaslevin is very busy at the moment and we would welcome new maintainers and help for the official Piwik iOS SDK :+1: if you are interested please consider opening pull requests. We could also give you commit access once you have contributed some things  :-) Thank you for your consideration!

**Comment by mattab** [comment]
FYI:  we the Piwik team are looking for a maintainer for the iOS SDK. if you can help please comment here #91 - we need you!

**Comment by JekaNaloyko** [comment]
I'll need to refactor the SDK to Swift, as I don't want to use AFNetworking. Already using Alamofire. Will comment here after prototyping the approach.

**Comment by SteamGorilla** [comment]
Hi @mattab what's up about the Swift portage for piwik ?

**Comment by mattab** [comment]
@SteamGorilla we are still looking for a volunteer to step up and take over the Piwik iOS SDK project. Would anyone be interested? 

It's a unique opportunity to help participate in a successful open source project and make a difference. We posted on twitter recently asking for help: 
![ios](https://cloud.githubusercontent.com/assets/466765/18828591/0cde4754-8435-11e6-808e-eb2f11e46acc.png)

**Comment by SteamGorilla** [comment]
@mattab Okay, thanks for your answer. I'm not already skilled enough to realize a portage by myself :/

**Comment by mattab** [comment]
Hi everyone, great news: @brototyp is working on a Swift 3 port of the iOS SDK. Please check it here: #96 and report your feedback to help him on his mission. The future of iOS SDK is here!

**Comment by brototyp** [comment]
After the first feedback by @mattiaslevin I realized that the pull request is by far to huge. So I will try to chunk if off into reviewable parts.

First will be a pull request with most objc files removed, new target setup and other project settings. Following pull requests will be separated parts. For example event queuing, dispatching, persisting settings and such.

I am looking forward to any feedback on my plan or, of cause, the pull requests.

**Comment by brototyp** [comment]
I got the first pull request prepared with just project setup over here: #97

**Comment by brototyp** [comment]
Seines we now have a base branch for the swift3 rewrite I will start a list of all things to write in swift so single parts can be picked and implemented separately. One might be inspired by the ideas over in #96 

- **PiwikConstants**: A collection of all constants. API, Userdefaults, parameters, ...
- **PiwikUserDefaults**: A wrapper onto NSUserDefaults that holds all stored values (except events) such as totalNumberOfVisits, firstVisit and such. 
- **UIDevice-Extension**: An extension to return the device platform (iPhone1,1), platform name (iPhone 1G), screen size and version of the operating system.
- **UIApplication-Extension**: An extension to return application specific values such as name, version, build version and such
- Models for **Event**, **Campaign**, **Transaction** and **CustomVariable**
- Protocol for an **EventQueue** 
- Protocol for a **Dispatcher**
- **PiwikTrackedViewController**
- the **PiwikTracker** itself

I guess separate tickets for each of those is the best idea. What do you think? 
@thorstenstark is there any of those you want to tackle?

**Comment by thorstenstark** [comment]
Yes, I would agree on this. Perhaps it would make sense to split the last two into seperate tickets. I haven't looked into the current implementation of them, but it sound like these two could be a bit more complex...
I would start with some low hanging fruits like the extensions of Device and Application to become acquainted with this project.

**Comment by brototyp** [comment]
The PiwikTrackedViewController is actually very short. It just tracks on `viewDidAppear:`. For all those points I am very open to splitting them up into smaller chunks. That goes especially for the `PiwikTracker` but the Dispatcher and the EventQueue can get big.

**Comment by brototyp** [comment]
Hi, thank you for your Pull Request. We dropped ongoing development for version 3 of this SDK. Please consider looking into version 4, which is completely rewritten in Swift.
