### ISSUE TITLE
Request a HTTP 204 code when tracking instead of a gif image

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik-sdk-ios#55]
See piwik/piwik#6577

Not sure if useful for iOS SDK or not but wanted to mention it. By sending URL parameter `&send_image=0` you would receive a HTTP 204 response code instead of a GIF image which is slightly faster.

**Comment by Cousin-Hub** [comment]
Have you tried? Because IOS does not handle correctly 204 response.

**Comment by mattiaslevin** [comment]
Fixed.
