### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by chowerton** [piwik/piwik-sdk-ios#56]
It would be nice if I could use this API to also build an Opt-In/Out list for an iOS App. There are lots of web-based systems for this, but none for native iOS apps.  Fields would be: email, first name, last name, state (opt-in or opt-out).

**Comment by mattab** [comment]
as @mattiaslevin pointed out:

> I think this is a great idea for a separate project and since I double both as iOS and backend developer I can probably do all/most of the parts needed. I will ask some fiends at work if they like to help out. If so I will set up a separate Github project for this.
