### ISSUE TITLE
Upload to app store failed because of @dynamic requestParameters 

### ISSUE THREAD

**Issue by benstadin** [piwik/piwik-sdk-ios#61]
Hi,

We have been using the library for a while. But just now an upload to the app store failed with a message like this:

"iTunes Store operation failed.
the app references non-public selectors in ... requestParameters, setRequestParameters"

That refers to PTEventEntity.h:
@property (nonatomic, retain) NSData * requestParameters;

The issue is for likely internal reasons / changes to the CoreData SDK caused by the dynamic declaration in the .m:
@dynamic requestParameters;

I guess Apple introduced a new private and undocumented property with the same name, and this is what now causes the issue. 

Renaming this property to piwikRequestParameters made the app pass the app store API verification.

Cheers
Ben

**Comment by mattiaslevin** [comment]
Fixed.
Renamed requestParameters to piwikRequestParameters in a new version of the data model.
Enabled CoreData lightweight data migration and added a unit test for testing the migration for v1 to v2.
