### ISSUE TITLE
Can't track a download using PiwikTracker iOS SDK

### ISSUE THREAD

**Issue by hnaethe** [piwik/piwik-sdk-ios#69]
Hi guys,

so I want to track if a user using my mobile app starts downloading a file so that the downloaded file name appears as entry under Actions>Downloads in the Piwik backend. I can't seem to do that using the PiwikTracker iOS SDK. I tried using the sendEventWithCategory method but then the entry appears under Events but not under Downloads like where I wanted it to be. How can I achieve it then?

Any help would be appreciated.

**Comment by mattiaslevin** [comment]
Tracked events will be shown under events in Piwik Server, not download.

I just added a new method to the API `sendDownload:(NSString)*url` for tracking downloads.
It has also been added to the demo project as example.

No release yet but you can pull down the latest version if you like to try it out.

**Comment by mattiaslevin** [comment]
Readme and API documentation updated.
Closing.

**Comment by perfectpapa** [comment]
does piwik ios sdk support https url?
