### ISSUE TITLE
[Question] iOS8 support

### ISSUE THREAD

**Issue by kampfgnu** [piwik/piwik-sdk-ios#71]
hi,

i just recognized that the library wasn't updated since dec. 17th, 2014.
there wasn't made any effort in supporting iOS8. (function "- (NSString *)platformName" of PiwikTracker does not even contain the iPhone6/6+)
did you guys stop working on the project
would be sad as this is a really cool library.

cheers

**Comment by mattiaslevin** [comment]
Been busy, sorry.
Fixed.
