### ISSUE TITLE
Piwik-iOS Event tracker issue.

### ISSUE THREAD

**Issue by issueli** [piwik/piwik-sdk-ios#72]
Server version : 2.12.1
piwik-iOS-sdk version : 2.5

1.set parameters according document .
2.call method [sendEventWithCategory:@"Event" action:"Launch_App" label:nil];

expected result :
The event will show in "Dashboard->Actions->Events" .
But real result:
The event show in "Dashboard->Actions->Pages" , and "Dashboard->Actions->Events" no data report.

and I call method [sendView:"LoginView"]; also will show in "Dashboard->Actions->Pages".
How can I do that make the event will show in "Dashboard->Actions->Events" ?

Please help me to fix this bug, thanks!

**Comment by mattiaslevin** [comment]
Older versions of the Piwik server only had support for page views. The Piwik SDK still offered an API for reporting event, but they were shown under "Dashboard->Actions->Pages"

Then the Piwik server offered a dedicated section for showing events and the SDK was updated to send events to this section.

I think you are using an old version of the Piwik SDK that are still sending events as page view. If you change to a new version of the Piwik SDK I think you should be fine.

**Comment by mattiaslevin** [comment]
Closing for now.

**Comment by minhkte** [comment]
@mattiaslevin 
Exactly which version got this issues?

Thanks

**Comment by mattiaslevin** [comment]
If I remember correctly the event support was added in Piwik server 2.3.
Support in the SDK was added June 2014 in commit 5b1fb06835a112f3c004eac10cf845ee0cf38459 (both the new and the legacy way to reporting was supported in parallel for some time).

The first official release of the SDK through CocoaPods that included this change was 3.0.0.
