### ISSUE TITLE
Add Platform

### ISSUE THREAD

**Issue by slecoustre** [piwik/piwik-sdk-ios#77]
It's possible add new platform?

thank

**Comment by mattiaslevin** [comment]
Certainly.
Feel free to create a pull request or add the code in here in the ticket. Or I will try to dig up the info later.

**Comment by slecoustre** [comment]
Hello

    if ([platform isEqualToString:@"iPhone8,1"])    return @"iPhone 6s+";
    if ([platform isEqualToString:@"iPhone8,2"])    return @"iPhone 6s";
    if ([platform isEqualToString:@"iPod7,1"])      return @"iPod Touch 6G";
    if ([platform isEqualToString:@"iPad5,1"])      return @"iPad Mini 4 (A1538)";
    if ([platform isEqualToString:@"iPad5,2"])      return @"iPad Mini 4 (A1550)";


thank

**Comment by Erulezz** [comment]
I created a pull request with the new devices.

**Comment by brototyp** [comment]
Hi, thank you for your Pull Request. We dropped ongoing development for version 3 of this SDK. Please consider looking into version 4, which is completely rewritten in Swift.
