### ISSUE TITLE
The data on the website is not counted my page

### ISSUE THREAD

**Issue by qy0731** [piwik/piwik-sdk-ios#79]
Hello, I first in APPDelagete configuration urls:

  [PiwikTracker sharedInstanceWithSiteID:@"1" baseURL:[NSURL URLWithString:@"https://52.68.54.67/piwik/"]];
   [PiwikTracker sharedInstance].userID = [NSString stringWithFormat:@"admin"];

Then, class to invoke this method:
    [[PiwikTracker sharedInstance]sendView:@"changeContentTwo"];

Then I called inside the click event:
    [[PiwikTracker sharedInstance] setCustomVariableForIndex:1 name:@"gender" value:@"man" scope:ScreenCustomVariableScope];
[[PiwikTracker sharedInstance] sendEventWithCategory:@"changeContentTwo" action:@"Play" name:@"Song12" value:@(2)];

This is my first time to use this thing, I don't know where have problem, the data did not show on the website,please help, thank you

**Comment by mattab** [comment]
Hello @qy0731 - do you still experience this issue?

**Comment by brototyp** [comment]
Closing for now. Please reopen if it still exists.
