### ISSUE TITLE
Deprecated in iOS 9

### ISSUE THREAD

**Issue by Erulezz** [piwik/piwik-sdk-ios#81]
There are a couple of deprecated things in iOS 8/9:
- PiwikLocationManager
  -- kCLAuthorizationStatusAuthorized
- PiwikTracker
  -- NSHourCalendarUnit

I'll will create a pull request soon with these issues resolved

**Comment by mattab** [comment]
Hi @Erulezz 

A pull request will be very welcome, thank you.

seancunningham

**Comment by mattab** [comment]
Hi @Erulezz 

A pull request will be very welcome, thank you.

FYI: we the Piwik team are looking for a maintainer for the iOS SDK. if you can help please comment here #91 - we need you!
