### ISSUE TITLE
Piwik iOS SDK recording the events in different order and session is not maintained.

### ISSUE THREAD

**Issue by prakashselvam** [piwik/piwik-sdk-ios#83]
1. The order in which the events are performed in app and the order in which the records stored in piwik db doesn't matches. Lot of irregular entries.
2. Events from previous session1 are recorded in next session2. If the entries are not pushed to server then they end-up in the very next session2 with a  visit id of session2, which is not the expected behavior. 
3. Forcefully starting a session doesn't work. "[[PiwikTracker sharedInstance] setSessionStart:TRUE];"

**Comment by prakashselvam** [comment]
I'm willing to provide sample data if needed.

**Comment by mattab** [comment]
Thanks for the report. Would you maybe be able to create a pull request to fix this issue?

FYI: we the Piwik team are looking for a maintainer for the iOS SDK. if you can help please comment here #91 - we need you!

**Comment by brototyp** [comment]
Hi, thank you for your Pull Request. We dropped ongoing development for version 3 of this SDK. Please consider looking into version 4, which is completely rewritten in Swift.
