### ISSUE TITLE
NSPersistentStoreCoordinator has no persistent stores (unknown)

### ISSUE THREAD

**Issue by cschleinkofer** [piwik/piwik-sdk-ios#85]
Sometimes there is thrown an exception in the PiwikTracker.m file in line 1456.
The save call of the managedObjectContext throws the following exception.

`*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'This NSPersistentStoreCoordinator has no persistent stores (unknown). It cannot perform a save operation.'`

**Comment by mattab** [comment]
Thanks for the report. Would you maybe be able to create a pull request to fix this issue?

FYI:  we the Piwik team are looking for a maintainer for the iOS SDK. if you can help please comment here #91 - we need you!

**Comment by brototyp** [comment]
Closing this for now. Feel free to reopen if you have more information on this topic.

**Comment by maulikdhameliya** [comment]
I am getting crash while using react native SDK . Not all users but few users facing it. Logs taken from firebase Crashlytics
https://github.com/PiwikPRO/react-native-piwik-pro-sdk#readme


**[PiwikTracker storeEventWithParameters:type:completionBlock:]_block_invoke
NSInternalInconsistencyException - This NSPersistentStoreCoordinator has no persistent stores (schema mismatch or migration failure). It cannot perform a save operation.**


**Fatal Exception: NSInternalInconsistencyException
This NSPersistentStoreCoordinator has no persistent stores (schema mismatch or migration failure). It cannot perform a save operation.**

P.S. I am not iOS developer so cant help to fix this.
