### ISSUE TITLE
PiwikNSURLSessionDispatcher miss url encode process

### ISSUE THREAD

**Issue by CoderRoger** [piwik/piwik-sdk-ios#88]
The method sendSingleEventWithParameters has URLEncode process for queryParameters while sendBulkEventWithParameters has not! And it effects the custom variables which containing other languages such as Chinese

**Comment by mattab** [comment]
Hi @CoderRoger 
thanks for the report. Would you please create a pull request with the fix?

FYI:  we the Piwik team are looking for a maintainer for the iOS SDK. if you can help please comment here #91 - we need you!

**Comment by brototyp** [comment]
Hi @CoderRoger, thanks again for the report. Please test this issue with the new [swift 3 alpha](https://github.com/piwik/piwik-sdk-ios/tree/swift3) and reopen if the issue still exists. We don't support sending single events, at least for now.
