### ISSUE TITLE
iOS multiple piwik site id tracking support

### ISSUE THREAD

**Issue by divyaSattu** [piwik/piwik-sdk-ios#89]
can anyone help me to support multiple site id tracking for platform iOS developement

**Comment by brototyp** [comment]
Hi @divyaSattu, thanks for your request. We are currently rewriting the SDK in Swift and consider supporting multiple Piwik Backends. Can you elaborate your need. Especially your scenario in in which you need to talk to two different backends.

**Comment by brototyp** [comment]
I moved the discussion over to #118.
