### ISSUE TITLE
tracker-proxy support

### ISSUE THREAD

**Issue by hector28933** [piwik/piwik-sdk-ios#90]
From the source code, it looks like using the tracker-proxy at https://github.com/piwik/tracker-proxy should work (it works with the Android SDK), at PiwikTracker.m we have:

```
if ([lastPathComponent isEqualToString:@"piwik.php"] || [lastPathComponent isEqualToString:@"piwik-proxy.php"]) {
    baseURL = [baseURL URLByDeletingLastPathComponent];
  }
```

But it doesn't seem to work. (Our code works directly against the piwik server).

Is piwik-sdk-ios tested against tracker-proxy?
Is there any workaround needed?

**Comment by mattab** [comment]
Hi @hector28933 @tiopez Maybe you are able to troubleshoot this issue further and figure out where is the problem, ie. is the HTTP request sent correctly by the SDK? is it sent to the right URL? 

At the moment we are looking for a maintainer for the iOS SDK so if you can help, please comment:https://github.com/piwik/piwik-sdk-ios/issues/91

**Comment by brototyp** [comment]
I am closing the issue for now. Please test this issue with the new [swift 3 alpha](https://github.com/piwik/piwik-sdk-ios/tree/swift3) and reopen the issue if you can provide more detailed information.
