### ISSUE TITLE
Are you an iOS developer? Help us maintain and improve the Piwik iOS SDK 

### ISSUE THREAD

**Issue by mattab** [piwik/piwik-sdk-ios#91]
At Piwik our goal is to help everyone measure their work and applications, and keep control of their data. As part of this mission, creating and maintaining [our official SDKs](http://developer.piwik.org/guides/tracking-api-clients) is a key activity of the Piwik team.

Mattias Levin has done a great job creating our Piwik iOS SDK and releasing several updates in the last few years. As Mattias is not available any more to maitain the SDK, we the [Piwik team](http://piwik.org/team/) are looking for a maintainer for the Piwik iOS SDK project!

**Are you experienced in iOS and interested to contribute to a big open source project, to make our iOS SDK awesome? please leave a message here, we would love to work with you!**

**Comment by mattab** [comment]
Hello @mattiaslevin - thank you so much for your work so far! Hopefully, someone else will step up to manage the project and move it forward :+1: be well!

**Comment by sebleclerc** [comment]
Hi @mattab, I'd like to maintain this project since I do use Piwik and the SDK. I'd like to know more about what is required to get involved with this project (workload, meetings?, other). Thanks!

**Comment by mattab** [comment]
Hi @sebleclerc 

That's great to hear! 

Currently the project is managed by @brototyp along with @thorstenstark who are leading the Swift rewrite project. They are also quite new to the project and have volunteered. They are assisted by @mattiaslevin the original creator of the SDK who is helping with code reviewing the new swift rewrite. 

So if you'd like to help I suggest you either comment here and introduce how you can help, and/or directly jump into the existing Pull requests to review them, and/or create new pull requests (after consulting with @brototyp) 

We're looking forward to your support!

**Comment by brototyp** [comment]
Hi @sebleclerc, thanks for the offer to help us. Aside of reviewing the pull request the best steps would be to pick one of the tickets that are in the "Swift Rewrite" Milestone. Most of them do not really describe the task well, or at all. Please don't hesitate to discuss with either directly me or in the issue.

**Comment by sebleclerc** [comment]
Thanks @brototyp ! I'll have a look at the pull request and Swift migration / rewrite

**Comment by akshaykolte** [comment]
Hi guys. I am up for it. We have been using the Objc SDK for a while and it crashed randomly quite often. Hence we wrote a Swift wrapper which directly called the Piwik server API to log events. It is quite similar to our current Swift SDK that is being developed here. I'd love to pick up an issue and start working on it. Let me know any thing you want me to pick on priority.

**Comment by brototyp** [comment]
Hi @akshaykolte, thank you for your message. That sounds awesome! We have a [CONTRIBUTING.md](https://github.com/piwik/piwik-sdk-ios/blob/develop/CONTRIBUTING.md) that helps a bit with the on boarding. First of all please discuss in all tickets. We are big fans of discussing and bouncing ideas around.
If you want to dive into implementing features right away I think #149 is a good starter. Please let me know if you have questions or need anything.

**Comment by brototyp** [comment]
I am closing this for now. Help is still very welcome!
