### ISSUE TITLE
Support for adding custom 'page title' and 'URL' as seperate parameters for sendViews()

### ISSUE THREAD

**Issue by arunmdavid** [piwik/piwik-sdk-ios#92]
We have an android application and the Piwik 'sendScreenView()' had option to pass an 'URL' and the 'Page Title' as separate parameters and I am able to see that in the Piwik visitor log. 
But when I try to do the same with the Piwik iOS SDK, It only supports one parameter which is same for 'Page Title' and 'URL' field in Piwik Dashboard. Can I able to user custom 'Page Title' and different 'URL' using the 'sendViews()' method in the iOS SDK?

**Comment by brototyp** [comment]
Hi @arunmdavid, thanks for your suggestion. We are currently rewriting the SDK in swift and will try to respect this improvement request.

**Comment by brototyp** [comment]
Should we make it possible to not only set the url on views, but also events? What would the url of an event say something about? I see the point for a website, but for an app?

**Comment by brototyp** [comment]
I just implemented setting the url when sending a view event. Once the pull request is merged this feature will be available in the next release of the 4.0.0 (Swift) version. Setting the url on other events will not be supported for now.
