### ISSUE TITLE
How do I track events with multiple parameters and not just the 4 that are available in sendEventwithCategory method?

### ISSUE THREAD

**Issue by akshaykolte** [piwik/piwik-sdk-ios#94]
I just need to capture some context with the event name and category.

**Comment by mattab** [comment]
Hello @akshaykolte 
you will need support for Custom Dimensions: https://piwik.org/docs/custom-dimensions/
At the moment though we are looking for a maintainer for the iOS SDK #91 for Custom Dimensions support to be added #82

**Comment by akshaykolte** [comment]
Hello Matthieu,

Thanks for the reply. We are currently adding extra fileds using Custom
Variables which are supported in the iOS SDK.

We have changed the number of custom variables from 5 to 10 on Piwik Server
Side Code.

However the custom variable key-value pair have a maximum length of 200
allowed.
Can you help us with changing this limit from 200 to something larger ? We
tried altering the column size of the tables on server-side but that
doesn't seem to help. Our string gets truncated to 200 chars.

Thanks,
Akshay Kolte
